### ISSUE TITLE
Unknown Error: Unknown filter category: genre 

### ISSUE THREAD

**Issue by brodybuster** [Kometa-Team/Kometa#111]
Started receding this error on or about 3/10 ... upgraded to latest version and still receiving this error. 

More info:
Traceback (most recent call last):|
|   File "/modules/config.py", line 461, in update_libraries
|     builder.run_methods(collection_obj, collection_name, rating_key_map, movie_map, show_map)
|   File "/modules/builder.py", line 684, in run_methods
|     items = self.library.Plex.search(**search_terms)
|   File "/usr/local/lib/python3.9/site-packages/plexapi/library.py", line 668, in search
|     args[category] = self._cleanSearchFilter(category, value, libtype)
|   File "/usr/local/lib/python3.9/site-packages/plexapi/library.py", line 717, in _cleanSearchFilter
|     raise BadRequest('Unknown filter category: %s' % category)
| plexapi.exceptions.BadRequest: Unknown filter category: genre
| 

Nothing has changed in my Movie.yml ... here is an excerpt:

Action:
    plex_search:
      genre: Action
    collection_order: alpha

  Adventure:
    plex_search:
      genre: Adventure
    collection_order: alpha

  Animation:
    plex_search:
      genre: Animation
    collection_order: alpha
  
  Biography:
    plex_search:
      genre: Biography
    collection_order: alpha
  
  Comedy:
    plex_search:
      genre: Comedy
    collection_order: alpha
  
  Crime:
    plex_search:
      genre: Crime
    collection_order: alpha
  
  Documentary:
    plex_search:
      genre: Documentary
    collection_order: alpha
  
  Family:
    plex_search:
      genre: Family
    collection_order: alpha
  
  Fantasy:
    plex_search:
      genre: Fantasy
    collection_order: alpha
  
  History:
    plex_search:
      genre: History
    collection_order: alpha
  
  Horror:
    plex_search:
      genre: Horror
    collection_order: alpha
  
  Music:
    plex_search:
      genre: Musical
    collection_order: alpha
  
  Romance:
    plex_search:
      genre: Romance
    collection_order: alpha
  
  Science-Fiction:
    plex_search:
      genre: Sci-Fi
    collection_order: alpha

  Sport:
    plex_search:
      genre: Sport
    collection_order: alpha

  Thriller:
    plex_search:
      genre: Thriller
    collection_order: alpha
    
  TV Movie:
    plex_search:
      genre: TV Movie
    collection_order: alpha    
  
  War:
    plex_search:
      genre: War
    collection_order: alpha
  
  Western:
    plex_search:
      genre: Western
    collection_order: alpha

None of these collections are updating as a result. My IMDB lists are fine.

**Comment by brodybuster** [comment]
Never mind ... I see this is related to Plex Search
