### ISSUE TITLE
AttributeError: 'MyLogger' object has no attribute 'infd'

### ISSUE THREAD

**Issue by mnkhouri** [Kometa-Team/Kometa#1173]
### Version Number

1.18.0

### What branch are you on?

master

### Describe the Bug

When attempting an overlay update, I see the following log:

```
| Loading All Movies from Library: Movies                                                            |
| Loaded 1899 Movies                                                                                 |
|                                                                                                    |
| Processing: 1/1899 [redacted]                                                                      |
| Traceback (most recent call last):                                                                 |
|   File "//plex_meta_manager.py", line 548, in run_libraries                                        |
|     run_operations_and_overlays()                                                                  |
|   File "//plex_meta_manager.py", line 511, in run_operations_and_overlays                          |
|     library_status[library.name]["Library Operations"] = library.Operations.run_operations()       |
|   File "/modules/operations.py", line 478, in run_operations                                       |
|     logger.infd(f"Poster | Reset from {poster_location}")                                          |
| AttributeError: 'MyLogger' object has no attribute 'infd'                                          |
|                                                                                                    |
| 'MyLogger' object has no attribute 'infd'
```

It appears this commit (https://github.com/meisnate12/Plex-Meta-Manager/commit/98ef43e7fa05e6edbb044ae7b0e7239cb5624298#diff-5aa0c4233a2f202666cef81ca865f6c4d36488b79f5c1ccbef2feed700738f12) accidentally referenced `logger.infd` instead of `logger.info`

### Logs

https://gist.github.com/mnkhouri/81d7cfad42c088152f28509292da00ef

**Comment by mnkhouri** [comment]
I see this was fixed https://github.com/meisnate12/Plex-Meta-Manager/commit/b3059eacfc95c1b402c87af20f609554b72389e1
