### ISSUE TITLE
Invalid Language Profile with Sonarr v4

### ISSUE THREAD

**Issue by MartinCa** [Kometa-Team/Kometa#1208]
### Version Number

1.18.0

### What branch are you on?

master

### Describe the Bug

In Sonarr v4 language profiles have been removed (https://forums.sonarr.tv/t/sonarr-v4-beta/31078). This gives an error when Plex-Meta-Manager tries to connect to Sonarr:
```
[2022-12-07 10:27:57,028] [config.py:923]             [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/sonarr.py", line 42, in __init__
                                                                 |     self.api._validate_add_options(params["root_folder_path"], params["quality_profile"], params["language_profile"])
                                                                 |   File "/usr/local/lib/python3.10/site-packages/arrapi/apis/sonarr.py", line 31, in _validate_add_options
                                                                 |     "language_profile": self._validate_language_profile(language_profile),
                                                                 |   File "/usr/local/lib/python3.10/site-packages/arrapi/apis/sonarr.py", line 430, in _validate_language_profile
                                                                 |     raise Invalid(f"Invalid Language Profile: '{language_profile}' Options: {options}")
                                                                 | arrapi.exceptions.Invalid: Invalid Language Profile: 'None' Options: [[1:Deprecated]]
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/modules/config.py", line 904, in __init__
                                                                 |     library.Sonarr = Sonarr(self, library, {
                                                                 |   File "/modules/sonarr.py", line 45, in __init__
                                                                 |     raise Failed(e)
                                                                 | modules.util.Failed: Invalid Language Profile: 'None' Options: [[1:Deprecated]]
                                                                 | 
[2022-12-07 10:27:57,029] [config.py:924]             [ERROR]    | Invalid Language Profile: 'None' Options: [[1:Deprecated]]
```

### Logs

https://gist.github.com/MartinCa/6f2f534dbdfce6e231ac7a3102eddd8e

**Comment by gbeynon99** [comment]
I see the same issue.

Edit: fixed on the nightly build
