### ISSUE TITLE
Unknown Error: 'ids' (Trending Collection)

### ISSUE THREAD

**Issue by talpazzo** [Kometa-Team/Kometa#121]
Hi! I'm having this error related to the "Trending Collections",
Version: 1.5.0, requirements upgraded, Synology. Plex version: 4.51.3. 

It was working until one week ago and I have a "Trending" collection in my plex.

Thank you, tAlpA

### Movies.yml
```
templates:
  Chart Alpha:
    sort_title: ++++++_<<num>><<collection_name>>
    sync_mode: sync
    collection_order: alpha
collections:

######################################################
#                Chart Collections                   #
######################################################

  Trending:
    template: {name: Chart Alpha, num: 2}
    trakt_trending: 40
    tmdb_trending_daily: 40
    tmdb_trending_weekly: 40
    summary: Movies Trending across the internet

```

### meta.log
```
[2021-03-18 13:41:41,508] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:41,508] [plex_meta_manager.py:61]   [INFO]     |                                                                                                    |
[2021-03-18 13:41:41,509] [plex_meta_manager.py:62]   [INFO]     |        ____  _             __  __      _          __  __                                           |
[2021-03-18 13:41:41,509] [plex_meta_manager.py:63]   [INFO]     |       |  _ \| | _____  __ |  \/  | ___| |_ __ _  |  \/  | __ _ _ __   __ _  __ _  ___ _ __         |
[2021-03-18 13:41:41,509] [plex_meta_manager.py:64]   [INFO]     |       | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|        |
[2021-03-18 13:41:41,510] [plex_meta_manager.py:65]   [INFO]     |       |  __/| |  __/>  <  | |  | |  __/ || (_| | | |  | | (_| | | | | (_| | (_| |  __/ |           |
[2021-03-18 13:41:41,510] [plex_meta_manager.py:66]   [INFO]     |       |_|   |_|\___/_/\_\ |_|  |_|\___|\__\__,_| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|           |
[2021-03-18 13:41:41,510] [plex_meta_manager.py:67]   [INFO]     |                                                                            |___/                   |
[2021-03-18 13:41:41,511] [plex_meta_manager.py:68]   [INFO]     |           Version: 1.5.0                                                                           |
[2021-03-18 13:41:41,511] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:41,511] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:41,512] [util.py:749]               [INFO]     |                                            Starting Run                                            |
[2021-03-18 13:41:41,512] [util.py:750]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:41,513] [config.py:27]              [INFO]     | Locating config...                                                                                 |
[2021-03-18 13:41:41,513] [config.py:32]              [INFO]     | Using /volume1/homes/admin/Plex-Meta-Manager/config/config.yml as config                           |
[2021-03-18 13:41:41,594] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:41,595] [cache.py:18]               [INFO]     | Using cache database at /volume1/homes/admin/Plex-Meta-Manager/config/config.cache                 |
[2021-03-18 13:41:41,596] [util.py:702]               [DEBUG]    | Config Warning: No Paths exist using ['/volume1/homes/admin/Plex-Meta-Manager/config/assets'] as default |
[2021-03-18 13:41:41,597] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:41,597] [config.py:165]             [INFO]     | Connecting to TMDb...                                                                              |
[2021-03-18 13:41:41,734] [config.py:171]             [INFO]     | TMDb Connection Successful                                                                         |
[2021-03-18 13:41:41,734] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:41,735] [config.py:179]             [INFO]     | Connecting to OMDb...                                                                              |
[2021-03-18 13:41:41,743] [config.py:186]             [INFO]     | OMDb Connection Successful                                                                         |
[2021-03-18 13:41:41,743] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:41,744] [config.py:194]             [INFO]     | Connecting to Trakt...                                                                             |
[2021-03-18 13:41:41,993] [config.py:204]             [INFO]     | Trakt Connection Successful                                                                        |
[2021-03-18 13:41:41,993] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:42,183] [config.py:213]             [INFO]     | Connecting to My Anime List...                                                                     |
[2021-03-18 13:41:42,184] [config.py:222]             [ERROR]    | Config Error: mal sub-attribute client_id is blank                                                 |
[2021-03-18 13:41:42,184] [config.py:223]             [INFO]     | My Anime List Connection Failed                                                                    |
[2021-03-18 13:41:42,799] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:42,803] [config.py:235]             [INFO]     | Connecting to Plex Libraries...                                                                    |
[2021-03-18 13:41:42,806] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:42,807] [config.py:275]             [INFO]     | Connecting to Film EN (Movies) Library...                                                          |
[2021-03-18 13:41:42,844] [plex.py:47]                [INFO]     | Using Asset Directory: /volume1/homes/admin/Plex-Meta-Manager/config/assets                        |
[2021-03-18 13:41:42,844] [config.py:326]             [INFO]     | Film EN Library Connection Successful                                                              |
[2021-03-18 13:41:42,845] [config.py:333]             [INFO]     | Connecting to Film EN library's Radarr...                                                          |
[2021-03-18 13:41:42,845] [util.py:702]               [DEBUG]    | Config Error: token attribute must be set under radarr globally or under this specific Library     |
[2021-03-18 13:41:42,845] [config.py:347]             [INFO]     | Film EN library's Radarr Connection Failed
[2021-03-18 13:41:42,845] [config.py:350]             [INFO]     | Connecting to Film EN library's Sonarr...
[2021-03-18 13:41:42,846] [util.py:702]               [DEBUG]    | Config Error: token attribute must be set under sonarr globally or under this specific Library
[2021-03-18 13:41:42,846] [config.py:365]             [INFO]     | Film EN library's Sonarr Connection Failed
[2021-03-18 13:41:42,846] [config.py:368]             [INFO]     | Connecting to Film EN library's Tautulli...
[2021-03-18 13:41:42,879] [config.py:376]             [INFO]     | Film EN library's Tautulli Connection Successful
[2021-03-18 13:41:42,879] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:42,880] [config.py:383]             [INFO]     | 1 Plex Library Connection Successful                                                               |
[2021-03-18 13:41:42,880] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:42,880] [config.py:392]             [INFO]     |                                                                                                    |
[2021-03-18 13:41:42,881] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:42,881] [util.py:749]               [INFO]     |                                          Film EN Library                                           |
[2021-03-18 13:41:42,881] [util.py:750]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:42,881] [config.py:394]             [INFO]     |                                                                                                    |
[2021-03-18 13:41:42,882] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:42,882] [util.py:749]               [INFO]     |                                      Mapping Film EN Library                                       |
[2021-03-18 13:41:42,882] [util.py:750]               [INFO]     |====================================================================================================|
[2021-03-18 13:41:42,882] [config.py:396]             [INFO]     |                                                                                                    |
[2021-03-18 13:41:42,883] [config.py:648]             [INFO]     | Mapping Movie Library: Film EN                                                                     |
[2021-03-18 13:42:02,241] [util.py:759]               [INFO]     | Processed 1305 Movies                                                                              |
[2021-03-18 13:42:02,267] [plex.py:223]               [INFO]     |                                                                                                    |
[2021-03-18 13:42:02,268] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:42:02,268] [util.py:749]               [INFO]     |                                      Film EN Library Metadata                                      |
[2021-03-18 13:42:02,268] [util.py:750]               [INFO]     |====================================================================================================|
[2021-03-18 13:42:02,268] [plex.py:225]               [INFO]     |                                                                                                    |
[2021-03-18 13:42:02,269] [config.py:402]             [ERROR]    | No metadata to edit                                                                                |
[2021-03-18 13:42:02,269] [config.py:403]             [INFO]     |                                                                                                    |
[2021-03-18 13:42:02,269] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:42:02,269] [util.py:749]               [INFO]     |                                    Film EN Library Collections                                     |
[2021-03-18 13:42:02,269] [util.py:750]               [INFO]     |====================================================================================================|
[2021-03-18 13:42:02,270] [config.py:423]             [INFO]     |                                                                                                    |
[2021-03-18 13:42:02,270] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:42:02,270] [util.py:749]               [INFO]     |                                        Trending Collection                                         |
[2021-03-18 13:42:02,270] [util.py:750]               [INFO]     |====================================================================================================|
[2021-03-18 13:42:02,271] [config.py:425]             [INFO]     |                                                                                                    |
[2021-03-18 13:42:02,271] [builder.py:192]            [INFO]     | Scanning Trending Collection                                                                       |
[2021-03-18 13:42:02,271] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-18 13:42:02,271] [builder.py:220]            [DEBUG]    | Method: template                                                                                   |
[2021-03-18 13:42:02,272] [builder.py:221]            [DEBUG]    | Value: ordereddict([('name', 'Chart Alpha'), ('num', 2)])                                          |
[2021-03-18 13:42:02,272] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-18 13:42:02,272] [builder.py:220]            [DEBUG]    | Method: trakt_trending                                                                             |
[2021-03-18 13:42:02,272] [builder.py:221]            [DEBUG]    | Value: 40                                                                                          |
[2021-03-18 13:42:02,273] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-18 13:42:02,273] [builder.py:220]            [DEBUG]    | Method: tmdb_trending_daily                                                                        |
[2021-03-18 13:42:02,273] [builder.py:221]            [DEBUG]    | Value: 40                                                                                          |
[2021-03-18 13:42:02,273] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-18 13:42:02,273] [builder.py:220]            [DEBUG]    | Method: tmdb_trending_weekly                                                                       |
[2021-03-18 13:42:02,273] [builder.py:221]            [DEBUG]    | Value: 40                                                                                          |
[2021-03-18 13:42:02,273] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-18 13:42:02,274] [builder.py:220]            [DEBUG]    | Method: summary                                                                                    |
[2021-03-18 13:42:02,274] [builder.py:221]            [DEBUG]    | Value: Movies Trending across the internet                                                         |
[2021-03-18 13:42:02,274] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-18 13:42:02,274] [builder.py:220]            [DEBUG]    | Method: sort_title                                                                                 |
[2021-03-18 13:42:02,274] [builder.py:221]            [DEBUG]    | Value: ++++++_2Trending                                                                            |
[2021-03-18 13:42:02,274] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-18 13:42:02,274] [builder.py:220]            [DEBUG]    | Method: sync_mode                                                                                  |
[2021-03-18 13:42:02,274] [builder.py:221]            [DEBUG]    | Value: sync                                                                                        |
[2021-03-18 13:42:02,275] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-18 13:42:02,275] [builder.py:220]            [DEBUG]    | Method: collection_order                                                                           |
[2021-03-18 13:42:02,275] [builder.py:221]            [DEBUG]    | Value: alpha                                                                                       |
[2021-03-18 13:42:02,288] [config.py:448]             [INFO]     |                                                                                                    |
[2021-03-18 13:42:02,289] [config.py:450]             [INFO]     | Sync Mode: sync                                                                                    |
[2021-03-18 13:42:02,974] [builder.py:647]            [DEBUG]    |                                                                                                    |
[2021-03-18 13:42:02,974] [builder.py:648]            [DEBUG]    | Method: trakt_trending                                                                             |
[2021-03-18 13:42:02,974] [builder.py:649]            [DEBUG]    | Values: [40]                                                                                       |
[2021-03-18 13:42:02,974] [builder.py:669]            [INFO]     |                                                                                                    |
[2021-03-18 13:42:02,975] [builder.py:670]            [DEBUG]    | Value: 40                                                                                          |
[2021-03-18 13:42:02,975] [trakttv.py:145]            [DEBUG]    | Data: 40                                                                                           |
[2021-03-18 13:42:03,509] [util.py:702]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/volume1/homes/admin/Plex-Meta-Manager/modules/config.py", line 462, in update_libraries
                                                                 |     builder.run_methods(collection_obj, collection_name, rating_key_map, movie_map, show_map)
                                                                 |   File "/volume1/homes/admin/Plex-Meta-Manager/modules/builder.py", line 751, in run_methods
                                                                 |     elif "trakt" in method:                             items_found += check_map(self.config.Trakt.get_items(method, value, self.library.is_movie))
                                                                 |   File "/volume1/homes/admin/Plex-Meta-Manager/modules/trakttv.py", line 149, in get_items
                                                                 |     movie_ids, show_ids = self.get_pagenation(method[6:], data, is_movie)
                                                                 |   File "/volume1/homes/admin/Plex-Meta-Manager/modules/trakttv.py", line 116, in get_pagenation
                                                                 |     if is_movie:            return [item["ids"]["tmdb"] for item in items], []
                                                                 |   File "/volume1/homes/admin/Plex-Meta-Manager/modules/trakttv.py", line 116, in <listcomp>
                                                                 |     if is_movie:            return [item["ids"]["tmdb"] for item in items], []
                                                                 | KeyError: 'ids'
                                                                 | 
[2021-03-18 13:42:03,511] [config.py:477]             [ERROR]    | Unknown Error: 'ids'
[2021-03-18 13:42:03,512] [config.py:480]             [INFO]     | 
[2021-03-18 13:42:03,512] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:42:03,512] [util.py:749]               [INFO]     |                              Unmanaged Collections in Film EN Library                              |
[2021-03-18 13:42:03,512] [util.py:750]               [INFO]     |====================================================================================================|
----> removed
[2021-03-18 13:42:03,996] [plex_meta_manager.py:88]   [INFO]     |                                                                                                    |
[2021-03-18 13:42:03,997] [util.py:745]               [INFO]     |====================================================================================================|
[2021-03-18 13:42:03,997] [util.py:749]               [INFO]     |                                            Finished Run                                            |
[2021-03-18 13:42:03,997] [util.py:749]               [INFO]     |                                         Run Time: 0:00:22                                          |
[2021-03-18 13:42:03,997] [util.py:750]               [INFO]     |====================================================================================================|

```

**Comment by meisnate12** [comment]
ok fix should be in develop

**Comment by talpazzo** [comment]
Thank you for your hard work!
