### ISSUE TITLE
Non-descriptive Traceback error

### ISSUE THREAD

**Issue by Bod1985** [Kometa-Team/Kometa#123]
I'm getting the following error on first run.

```
2021-03-18T14:33:11.206142411Z |====================================================================================================|

2021-03-18T14:33:11.206210233Z |====================================================================================================|

2021-03-18T14:33:11.206262622Z |                                            Starting Run                                            |

2021-03-18T14:33:11.206309424Z |====================================================================================================|

2021-03-18T14:33:11.206366968Z | Locating config...                                                                                 |

2021-03-18T14:33:11.206432364Z | Using /config/config.yml as config                                                                 |

2021-03-18T14:33:11.232516229Z |====================================================================================================|

2021-03-18T14:33:11.232951910Z | Using cache database at /config/config.cache                                                       |

2021-03-18T14:33:11.233187651Z | Config Warning: No Paths exist using ['/config/assets'] as default                                 |

2021-03-18T14:33:11.233282641Z |====================================================================================================|

2021-03-18T14:33:11.233374798Z | Connecting to TMDb...                                                                              |

2021-03-18T14:33:11.321028501Z | TMDb Connection Successful                                                                         |

2021-03-18T14:33:11.321053346Z |====================================================================================================|

2021-03-18T14:33:11.321207883Z | Connecting to OMDb...                                                                              |

2021-03-18T14:33:11.379224392Z | OMDb Error: Invalid API key!                                                                       |

2021-03-18T14:33:11.379261973Z | OMDb Connection Failed                                                                             |

2021-03-18T14:33:11.379299811Z |====================================================================================================|

2021-03-18T14:33:11.379474488Z | Connecting to Trakt...                                                                             |

2021-03-18T14:33:11.570177765Z | Trakt Connection Successful                                                                        |

2021-03-18T14:33:11.570193174Z |====================================================================================================|

2021-03-18T14:33:11.862679888Z | mal attribute not found                                                                            |

2021-03-18T14:33:12.195530052Z |====================================================================================================|

2021-03-18T14:33:12.197062045Z | Connecting to Plex Libraries...                                                                    |

2021-03-18T14:33:12.198596956Z |====================================================================================================|

2021-03-18T14:33:12.198648198Z | Connecting to Movies-4K Library...                                                                 |

2021-03-18T14:33:12.859521012Z | Traceback (most recent call last):                                                                 |

2021-03-18T14:33:12.859600399Z |   File "//plex_meta_manager.py", line 105, in start                                                |

2021-03-18T14:33:12.859627918Z |     config = Config(default_dir, config_path)                                                      |

2021-03-18T14:33:12.859659317Z |   File "/modules/config.py", line 325, in __init__                                                 |

2021-03-18T14:33:12.859704973Z |     library = PlexAPI(params, self.TMDb, self.TVDb)                                                |

2021-03-18T14:33:12.859799504Z |   File "/modules/plex.py", line 27, in __init__                                                    |

2021-03-18T14:33:12.859818761Z |     try:                                                                    self.data, ind, bsi = yaml.util.load_yaml_guess_indent(open(params["metadata_path"], encoding="utf-8")) |

2021-03-18T14:33:12.859866972Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/util.py", line 120, in load_yaml_guess_indent |

2021-03-18T14:33:12.859908270Z |     return round_trip_load(yaml_str, **kw), indent, block_seq_indent                               |

2021-03-18T14:33:12.859951642Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/main.py", line 1016, in round_trip_load |

2021-03-18T14:33:12.859992155Z |     return load(stream, RoundTripLoader, version, preserve_quotes=preserve_quotes)                 |

2021-03-18T14:33:12.860037017Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/main.py", line 951, in load             |

2021-03-18T14:33:12.860077528Z |     return loader._constructor.get_single_data()                                                   |

2021-03-18T14:33:12.860122386Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 113, in get_single_data |

2021-03-18T14:33:12.860165643Z |     return self.construct_document(node)                                                           |

2021-03-18T14:33:12.860206485Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 123, in construct_document |

2021-03-18T14:33:12.860251243Z |     for _dummy in generator:                                                                       |

2021-03-18T14:33:12.860293512Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1563, in construct_yaml_map |

2021-03-18T14:33:12.860334538Z |     self.construct_mapping(node, data, deep=True)                                                  |

2021-03-18T14:33:12.860378577Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1469, in construct_mapping |

2021-03-18T14:33:12.860425297Z |     value = self.construct_object(value_node, deep=deep)                                           |

2021-03-18T14:33:12.860469942Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 146, in construct_object |

2021-03-18T14:33:12.860510732Z |     data = self.construct_non_recursive_object(node)                                               |

2021-03-18T14:33:12.860555194Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object |

2021-03-18T14:33:12.860596335Z |     for _dummy in generator:                                                                       |

2021-03-18T14:33:12.860641144Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1563, in construct_yaml_map |

2021-03-18T14:33:12.860682327Z |     self.construct_mapping(node, data, deep=True)                                                  |

2021-03-18T14:33:12.860734710Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1469, in construct_mapping |

2021-03-18T14:33:12.860776398Z |     value = self.construct_object(value_node, deep=deep)                                           |

2021-03-18T14:33:12.860820172Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 146, in construct_object |

2021-03-18T14:33:12.860861373Z |     data = self.construct_non_recursive_object(node)                                               |

2021-03-18T14:33:12.860907739Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object |

2021-03-18T14:33:12.860948345Z |     for _dummy in generator:                                                                       |

2021-03-18T14:33:12.860993091Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1563, in construct_yaml_map |

2021-03-18T14:33:12.861033786Z |     self.construct_mapping(node, data, deep=True)                                                  |

2021-03-18T14:33:12.861078476Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1470, in construct_mapping |

2021-03-18T14:33:12.861119517Z |     if self.check_mapping_key(node, key_node, maptyp, key, value):                                 |

2021-03-18T14:33:12.861164236Z |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 295, in check_mapping_key |

2021-03-18T14:33:12.861205549Z |     raise DuplicateKeyError(*args)                                                                 |

2021-03-18T14:33:12.861249997Z | ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping                            |

2021-03-18T14:33:12.861291518Z |   in "<unicode string>", line 1290, column 5:                                                      |

2021-03-18T14:33:12.861336178Z |         plex_collectionless:                                                                       |

2021-03-18T14:33:12.861378008Z |         ^ (line: 1290)                                                                             |

2021-03-18T14:33:12.861422820Z | found duplicate key "collection_order" with value "alpha" (original value: "alpha")                |

2021-03-18T14:33:12.861463896Z |   in "<unicode string>", line 1296, column 5:                                                      |

2021-03-18T14:33:12.861508761Z |         collection_order: alpha                                                                    |

2021-03-18T14:33:12.861550163Z |         ^ (line: 1296)                                                                             |

2021-03-18T14:33:12.861595639Z |                                                                                                    |

2021-03-18T14:33:12.861636942Z | To suppress this check see:                                                                        |

2021-03-18T14:33:12.861681053Z |     http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys                                   |

2021-03-18T14:33:12.861722633Z |                                                                                                    |

2021-03-18T14:33:12.861767300Z | Duplicate keys will become an error in future releases, and are errors                             |

2021-03-18T14:33:12.861813222Z | by default when using the new API.                                                                 |

2021-03-18T14:33:12.861857486Z |                                                                                                    |

2021-03-18T14:33:12.861910785Z |                                                                                                    |

2021-03-18T14:33:12.862101105Z | while constructing a mapping

2021-03-18T14:33:12.862105115Z   in "<unicode string>", line 1290, column 5:

2021-03-18T14:33:12.862107342Z         plex_collectionless:

2021-03-18T14:33:12.862109309Z         ^ (line: 1290)

2021-03-18T14:33:12.862111276Z found duplicate key "collection_order" with value "alpha" (original value: "alpha")

2021-03-18T14:33:12.862114425Z   in "<unicode string>", line 1296, column 5:

2021-03-18T14:33:12.862116438Z         collection_order: alpha

2021-03-18T14:33:12.862118372Z         ^ (line: 1296)

2021-03-18T14:33:12.862120289Z 

2021-03-18T14:33:12.862122213Z To suppress this check see:

2021-03-18T14:33:12.862124133Z     http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

2021-03-18T14:33:12.862126110Z 

2021-03-18T14:33:12.862128055Z Duplicate keys will become an error in future releases, and are errors

2021-03-18T14:33:12.862130085Z by default when using the new API.

2021-03-18T14:33:12.862132034Z  |

2021-03-18T14:33:12.862251970Z |                                                                                                    |

2021-03-18T14:33:12.862320835Z |====================================================================================================|

2021-03-18T14:33:12.862379810Z |                                            Finished Run                                            |

2021-03-18T14:33:12.862430893Z |                                         Run Time: 0:00:01                                          |

2021-03-18T14:33:12.862481698Z |====================================================================================================|
```

**Comment by bencmeyer** [comment]
Why was this closed?
I have the same issue.

**Comment by Bod1985** [comment]
> Why was this closed?
> I have the same issue.

I realised I hadn’t created the collections/metadata files. The wiki lacks clarity, if I find some time I’ll see if I can write up some improvements.
