### ISSUE TITLE
Can't use the decade filter

### ISSUE THREAD

**Issue by omerher** [Kometa-Team/Kometa#148]
Movies.yml:
```
templates:
  Year:
    decade: <<decade>>
    summary: A collection of movies released in the <<collection_name>>
    sort_title: '*<<num>>'
    collection_mode: default

collections:
  1970s:
    template: {name: Year, decade: 1970, num: '000'}
```

Logs:
```
|====================================================================================================|
|                                          1970s Collection                                          |
|====================================================================================================|
|                                                                                                    |
| Scanning 1970s Collection                                                                          |
|                                                                                                    |
| Method: template                                                                                   |
| Value: ordereddict([('name', 'Year'), ('decade', 1970), ('num', '000')])                           |
|                                                                                                    |
| Method: decade                                                                                     |
| Value: 1970                                                                                        |
|                                                                                                    |
| Method: summary                                                                                    |
| Value: A collection of movies released in the 1970s                                                |
|                                                                                                    |
| Method: sort_title                                                                                 |
| Value: *000                                                                                        |
|                                                                                                    |
| Method: collection_mode                                                                            |
| Value: default                                                                                     |
|                                                                                                    |
| Sync Mode: append                                                                                  |
|                                                                                                    |
| Method: plex_search                                                                                |
| Values: [{'decade': 1970}]                                                                         |
|                                                                                                    |
| Value: {'decade': 1970}                                                                            |
| Traceback (most recent call last):                                                                 |
|   File "D:\Documents\Plex Meta Manager\modules\config.py", line 462, in update_libraries           |
|     builder.run_methods(collection_obj, collection_name, rating_key_map, movie_map, show_map)      |
|   File "D:\Documents\Plex Meta Manager\modules\builder.py", line 824, in run_methods               |
|     for o, param in enumerate(search_data):                                                        |
| TypeError: 'int' object is not iterable                                                            |
|                                                                                                    |
| Unknown Error: 'int' object is not iterable                                                        |
|                                                                                                    |
|====================================================================================================|
```

**Comment by jameshoyt** [comment]
I get the same error. It seems to work if you do one year at a time instead of decade, obviously that wouldn't be ideal though.

**Comment by meisnate12** [comment]
fix is in develop

**Comment by jameshoyt** [comment]
I pulled from develop and that seemed to fix it. Thanks for resolving it.
