### ISSUE TITLE
tvdb_show not working

### ISSUE THREAD

**Issue by calboi91** [Kometa-Team/Kometa#18]
When filling the `tvdb_show` attribute, I get an error. If I fill with a URL, I get the following error:
```
[2021-02-11 08:50:08,969] [util.py:575]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/home9/calboi/Plex-Meta-Manager/modules/tvdb.py", line 124, in get_items
                                                                 |     try:                                                    show_ids.append(self.get_series(language, tvdb_id=int(data)))
                                                                 | ValueError: invalid literal for int() with base 10: 'https://www.thetvdb.com/series/beyond-the-boundary'
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/home9/calboi/Plex-Meta-Manager/modules/config.py", line 937, in update_libraries
                                                                 |     elif "tvdb" in method:                              items_found += check_map(self.TVDb.get_items(method, value, library.Plex.language))
                                                                 |   File "/home9/calboi/Plex-Meta-Manager/modules/tvdb.py", line 125, in get_items
                                                                 |     except ValueError:                                      show_ids.append(self.get_series(language, tmdb_url=data))
                                                                 | TypeError: get_series() got an unexpected keyword argument 'tmdb_url'
                                                                 | 
[2021-02-11 08:50:08,970] [config.py:1045]            [ERROR]    | Unknown Error: get_series() got an unexpected keyword argument 'tmdb_url'
```

If I fill with a TVDb ID, I get the following error:
```
[2021-02-11 08:50:41,961] [tvdb.py:122]               [INFO]     | Processing TVDb Show: 272697                                                                       |
[2021-02-11 08:50:42,713] [tvdb.py:136]               [DEBUG]    | TMDb IDs Found: []                                                                                 |
[2021-02-11 08:50:42,713] [tvdb.py:137]               [DEBUG]    | TVDb IDs Found: [<modules.tvdb.TVDbObj object at 0x7f82624adb20>]                                  |
[2021-02-11 08:50:42,713] [config.py:944]             [ERROR]    | No items found to add to this collection                                                           |
[2021-02-11 08:50:42,714] [config.py:947]             [INFO]     |                                                                                                    |
[2021-02-11 08:50:42,931] [config.py:969]             [ERROR]    | TVDb Error: Could not find a TVDb Series ID at the URL https://www.thetvdb.com/dereferrer/series/<modules.tvdb.TVDbObj object at 0x7f82624adb20> |
```

**Comment by meisnate12** [comment]
this should be fixed
