### ISSUE TITLE
Episode Metadata Season and Episode Numbering Mixed Up For Three Digit Seasons/Episodes

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#184]
I'm trying to update the summary of an episode, and it's giving me an error: "Metadata error: episode 309 of season 66 not found"

My config file:

```
metadata:
  "Series Name":
    episodes:
      S309E66:
        summary: >-
              Test content
              
--- This looks for S66E309, and fails because no episode found
```
              
However, if I change it to swap the season and episode number it works. The messaging in the console prints the incorrect episode (S66E309), but it's actually affecting S309E66.

```
metadata:
  "Series Name":
    episodes:
      S66E309:
        summary: >-
              Test content
              
--- This looks for S309E66, and succeeds because episode was found
```

**Comment by meisnate12** [comment]
fix is in develop

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
I'm experencing this issue on develop branch again.

@meisnate12

**Comment by meisnate12** [comment]
can you give me the output

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
In the YML config, Test Show is set to override the summary on S300E66, and the episode exists in Plex
```
[2021-04-22 17:43:27,879] [plex.py:795]               [INFO]     | Updating episode S66E300 of Test Show...                                                         |
[2021-04-22 17:43:28,030] [util.py:313]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 108, in start
                                                                 |     config.update_libraries(is_test, collections_to_run, resume_from)
                                                                 |   File "/modules/config.py", line 456, in update_libraries
                                                                 |     try:                        library.update_metadata(self.TMDb, test)
                                                                 |   File "/modules/plex.py", line 799, in update_metadata
                                                                 |     episode_dict = meta[methods["episodes"]][episode_str]
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/comments.py", line 826, in __getitem__
                                                                 |     return ordereddict.__getitem__(self, key)
                                                                 | KeyError: '66'
                                                                 | 
[2021-04-22 17:43:28,031] [plex_meta_manager.py:111]  [CRITICAL] | '66'
[2021-04-22 17:43:28,031] [plex_meta_manager.py:112]  [INFO]     | 
```

**Comment by meisnate12** [comment]
ok fix is in develop

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
It's updating episodes properly now. The messaging is still incorrect, where is says:
```
Updating episode S66E300 of Test Show...
Detail: title updated to ______________________
```

It should be
```
Updating episode S300E66 of Test Show...
Detail: title updated to ______________________
```
