### ISSUE TITLE
`imdb_search` builder `PersistedQueryNotFound` error

### ISSUE THREAD

**Issue by javierlopeza** [Kometa-Team/Kometa#1980]
### Version Number

1.21.0-nightly14

### What branch are you on?

nightly

### Describe the Bug

Using the `imdb_search` builder gives me the following error after a couple of PMM manual runs. Is this a rate limiting thing from IMDb end? Or something PMM could fix? Thanks for the great project! 💚
```
|============================= Running Popular in True Crime Collection =============================|
|                                                                                                    |
| Sync Mode: sync                                                                                    |
|                                                                                                    |
| Builder: imdb_search: {'limit': 5, 'type': ['tv_series', 'tv_mini_series'], 'country': ['US'], 'genre': ['documentary', 'crime'], 'release.after': '2020-01-01', 'rating.gte': 7.0, 'votes.gte': 1250, 'sort_by': 'rating.desc'} |
|                                                                                                    |
| Processing IMDb Search:                                                                            |
|     limit: 5                                                                                       |
|     type: ['tv_series', 'tv_mini_series']                                                          |
|     country: ['US']                                                                                |
|     genre: ['documentary', 'crime']                                                                |
|     release.after: 2020-01-01                                                                      |
|     rating.gte: 7.0                                                                                |
|     votes.gte: 1250                                                                                |
|     sort_by: rating.desc                                                                           |
| Response: {'errors': [{'message': 'PersistedQueryNotFound', 'extensions': {'code': 'PERSISTED_QUERY_NOT_FOUND'}}]} |
| Traceback (most recent call last):                                                                 |
|   File "//plex_meta_manager.py", line 783, in run_collection                                       |
|     builder.filter_and_save_items(builder.gather_ids(method, value))                               |
|                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                |
|   File "/modules/builder.py", line 2207, in gather_ids                                             |
|     ids = self.config.IMDb.get_imdb_ids(method, value, self.language)                              |
|           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                              |
|   File "/modules/imdb.py", line 540, in get_imdb_ids                                               |
|     return [(_i, "imdb") for _i in self._search(data)]                                             |
|                                    ^^^^^^^^^^^^^^^^^^                                              |
|   File "/modules/imdb.py", line 381, in _search                                                    |
|     total = response_json["data"]["advancedTitleSearch"]["total"]                                  |
|             ~~~~~~~~~~~~~^^^^^^^^                                                                  |
| KeyError: 'data'                                                                                   |
|                                                                                                    |
| Unknown Error: 'data'    
```

### Relevant Collection/Overlay/Playlist Definition

```yml
Popular in True Crime:
    template: { name: Chart, num: 5 }
    imdb_search:
      type: tv_series, tv_mini_series
      country: US
      genre: documentary,crime
      release.after: 2020-01-01
      rating.gte: 7.0
      votes.gte: 1250
      sort_by: rating.desc
      limit: 5
```

**Comment by YozoraXCII** [comment]
Can you try again now?

**Comment by javierlopeza** [comment]
Error still shows up after waiting more than 10 minutes

**Comment by javierlopeza** [comment]
Error went away now... not sure what it was. Maybe some throttling on IMDb side. Closing for now, thanks.

**Comment by YozoraXCII** [comment]
> Error went away now... not sure what it was. Maybe some throttling on IMDb side. Closing for now, thanks.

It was an issue on our side which I have resolved - thanks for confirming
