### ISSUE TITLE
When using plex_search, if studio value isn't found every show gets added to collection

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#199]
For some reason one of my studio collections went MIA today and is no longer available. Because of this, the collection I created errors/warns me:
```
Plex Error: studio ___ not found
Collection Warning: No valid studio values found in ___
```
And then proceeds to fill every existing show in the collection.

**Comment by meisnate12** [comment]
This fix is in develop

**Comment by meisnate12** [comment]
There's a fix for this in develop

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
I just pulled develop and I'm still having this issue. When I run the script it says it's running Version 1.7.2

**Comment by meisnate12** [comment]
in develop when i run 
```yaml
collections:
  +TEST:
    plex_search:
      studio: i dont have this in plex
```
the output is 
```
|====================================================================================================|
|                                          +TEST Collection                                          |
|====================================================================================================|
|                                                                                                    |
| Scanning +TEST Collection                                                                          |
|                                                                                                    |
| Validating Method: plex_search                                                                     |
| Value: ordereddict([('studio', 'i dont have this in plex')])                                       |
| Plex Error: studio: i dont have this in plex not found                                             |
| Collection Warning: No valid studio values found in i dont have this in plex                       |
| Collection Error: no valid plex search attributes                                                  |
|                                                                                                    |
|====================================================================================================|
```
do you see version 1.7.2-Beta1 at the start of your run that's the current version in develop

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
I didn't see that - I found the issue though. I had only upgraded my docker-compose version to develop, the command I was using was still on master.

There's something else breaking in this new branch though.

I get this error now:
```
|====================================================================================================|
|                                       Shows Library Metadata                                       |
|====================================================================================================|
|                                                                                                    |
|                                                                                                    |
|====================================================================================================|
|                                                                                                    |
| int() argument must be a string, a bytes-like object or a number, not 'NoneType'                   |
|                                                                                                    |
|====================================================================================================|
|                                            Finished Run                                            |
|                                         Run Time: 0:00:57                                          |
|====================================================================================================|
```

Switching back to master, everything works as expected.

**Comment by meisnate12** [comment]
Can you look in your meta.log file and post the trace back printing just before this line in the log

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
```
[2021-04-11 18:13:34,125] [util.py:356]               [INFO]     |====================================================================================================|
[2021-04-11 18:13:34,125] [util.py:360]               [INFO]     |                                       Shows Library Metadata                                       |
[2021-04-11 18:13:34,125] [util.py:361]               [INFO]     |====================================================================================================|
[2021-04-11 18:13:34,125] [plex.py:468]               [INFO]     |                                                                                                    |
[2021-04-11 18:13:34,125] [plex.py:475]               [INFO]     |                                                                                                    |
[2021-04-11 18:13:34,125] [util.py:356]               [INFO]     |====================================================================================================|
[2021-04-11 18:13:34,125] [plex.py:477]               [INFO]     |                                                                                                    |
[2021-04-11 18:14:24,187] [util.py:313]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 108, in start
                                                                 |     config.update_libraries(is_test, collections_to_run, resume_from)
                                                                 |   File "/modules/config.py", line 453, in update_libraries
                                                                 |     try:                        library.update_metadata(self.TMDb, test)
                                                                 |   File "/modules/plex.py", line 487, in update_metadata
                                                                 |     item = self.search_item(title, year=year)
                                                                 |   File "/modules/plex.py", line 463, in search_item
                                                                 |     return util.choose_from_list(self.search(data, year=year), "movie" if self.is_movie else "show", str(data), exact=True)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/retrying.py", line 49, in wrapped_f
                                                                 |     return Retrying(*dargs, **dkw).call(f, *args, **kw)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/retrying.py", line 212, in call
                                                                 |     raise attempt.get()
                                                                 |   File "/usr/local/lib/python3.9/site-packages/retrying.py", line 247, in get
                                                                 |     six.reraise(self.value[0], self.value[1], self.value[2])
                                                                 |   File "/usr/local/lib/python3.9/site-packages/six.py", line 703, in reraise
                                                                 |     raise value
                                                                 |   File "/usr/local/lib/python3.9/site-packages/retrying.py", line 200, in call
                                                                 |     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
                                                                 |   File "/modules/plex.py", line 186, in search
                                                                 |     return self.Plex.search(title=title, sort=sort, maxresults=maxresults, libtype=libtype, **kwargs)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/library.py", line 1128, in search
                                                                 |     filter_args.append(self._validateFilterField(field, values, libtype))
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/library.py", line 801, in _validateFilterField
                                                                 |     result = self._validateFieldValue(filterField, values, libtype)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/library.py", line 857, in _validateFieldValue
                                                                 |     value = int(value)
                                                                 | TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
                                                                 | 
[2021-04-11 18:14:24,188] [plex_meta_manager.py:111]  [CRITICAL] | int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2021-04-11 18:14:24,188] [plex_meta_manager.py:112]  [INFO]     | 
[2021-04-11 18:14:24,188] [util.py:356]               [INFO]     |====================================================================================================|
[2021-04-11 18:14:24,188] [util.py:360]               [INFO]     |                                            Finished Run                                            |
[2021-04-11 18:14:24,188] [util.py:360]               [INFO]     |                                         Run Time: 0:00:57                                          |
[2021-04-11 18:14:24,188] [util.py:361]               [INFO]     |====================================================================================================|
```

**Comment by meisnate12** [comment]
ok fixed that issue it was unrelated to the collection so update develop and try again

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Thanks! The int argument error is fixed, and missing studio values are fixed.

I'm seeing that same error the studio value had when a genre isn't found. And if that's happening, then it probably happens with others I haven't tested too



Also, it doesn't look like changing the title of the Special season works.

YML:
```
metadata:
  "Series Name":
    seasons:
      0:
        title: Test-Title
```
Error:
```
[2021-04-12 06:18:06,590] [plex.py:677]               [DEBUG]    | Season: 0 Details Update: {'title.value': 'Test-Title', 'title.locked': 1}                           |
[2021-04-12 06:18:06,602] [util.py:313]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 108, in start
                                                                 |     config.update_libraries(is_test, collections_to_run, resume_from)
                                                                 |   File "/modules/config.py", line 453, in update_libraries
                                                                 |     try:                        library.update_metadata(self.TMDb, test)
                                                                 |   File "/modules/plex.py", line 680, in update_metadata
                                                                 |     season.edit(**edits)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 497, in edit
                                                                 |     self._server.query(part, method=self._server._session.put)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 531, in query
                                                                 |     raise NotFound(message)
                                                                 | plexapi.exceptions.NotFound: (404) not_found; https://plex.hostname.com/library/sections/None/all?title.value=Test-Title&title.locked=1&id=209332&type=4 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
                                                                 | 
[2021-04-12 06:18:06,603] [plex_meta_manager.py:111]  [CRITICAL] | (404) not_found; https://plex.hostname.com/library/sections/None/all?title.value=Test-Title&title.locked=1&id=209332&type=4 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
[2021-04-12 06:18:06,603] [plex_meta_manager.py:112]  [INFO]     | 
```

**Comment by meisnate12** [comment]
this is actually a bug in the plexAPI i fixed it you can follow the Pull Request pkkid/python-plexapi/pull/725

**Comment by meisnate12** [comment]
added a workaround in develop so it should be good now
