### ISSUE TITLE
Unknown Error: IMDb Error: No IMDb IDs Found

### ISSUE THREAD

**Issue by omerher** [Kometa-Team/Kometa#206]
Starting happening a few days ago.

Log file:
```
[2021-04-14 03:02:18,441] [util.py:349]               [INFO]     |====================================================================================================|
[2021-04-14 03:02:18,441] [util.py:353]               [INFO]     |                                      IMDb Top 250 Collection                                       |
[2021-04-14 03:02:18,442] [util.py:354]               [INFO]     |====================================================================================================|
[2021-04-14 03:02:18,442] [config.py:486]             [INFO]     |                                                                                                    |
[2021-04-14 03:02:18,442] [builder.py:338]            [INFO]     | Scanning IMDb Top 250 Collection                                                                   |
[2021-04-14 03:02:18,442] [builder.py:366]            [DEBUG]    |                                                                                                    |
[2021-04-14 03:02:18,442] [builder.py:367]            [DEBUG]    | Validating Method: template                                                                        |
[2021-04-14 03:02:18,442] [builder.py:368]            [DEBUG]    | Value: ordereddict([('name', 'List'), ('imdb_url', 'https://www.imdb.com/search/title/?groups=top_250&count=250/'), ('summary', "IMDB's 250 top rated movies of all time."), ('num', '003')]) |
[2021-04-14 03:02:18,442] [builder.py:366]            [DEBUG]    |                                                                                                    |
[2021-04-14 03:02:18,442] [builder.py:367]            [DEBUG]    | Validating Method: imdb_list                                                                       |
[2021-04-14 03:02:18,442] [builder.py:368]            [DEBUG]    | Value: https://www.imdb.com/search/title/?groups=top_250&count=250/                                |
[2021-04-14 03:02:18,442] [builder.py:366]            [DEBUG]    |                                                                                                    |
[2021-04-14 03:02:18,442] [builder.py:367]            [DEBUG]    | Validating Method: summary                                                                         |
[2021-04-14 03:02:18,442] [builder.py:368]            [DEBUG]    | Value: IMDB's 250 top rated movies of all time.                                                    |
[2021-04-14 03:02:18,442] [builder.py:366]            [DEBUG]    |                                                                                                    |
[2021-04-14 03:02:18,442] [builder.py:367]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2021-04-14 03:02:18,443] [builder.py:368]            [DEBUG]    | Value: /003                                                                                        |
[2021-04-14 03:02:18,443] [builder.py:366]            [DEBUG]    |                                                                                                    |
[2021-04-14 03:02:18,443] [builder.py:367]            [DEBUG]    | Validating Method: collection_order                                                                |
[2021-04-14 03:02:18,443] [builder.py:368]            [DEBUG]    | Value: alpha                                                                                       |
[2021-04-14 03:02:18,443] [builder.py:366]            [DEBUG]    |                                                                                                    |
[2021-04-14 03:02:18,443] [builder.py:367]            [DEBUG]    | Validating Method: collection_mode                                                                 |
[2021-04-14 03:02:18,443] [builder.py:368]            [DEBUG]    | Value: default                                                                                     |
[2021-04-14 03:02:18,443] [builder.py:366]            [DEBUG]    |                                                                                                    |
[2021-04-14 03:02:18,443] [builder.py:367]            [DEBUG]    | Validating Method: sync_mode                                                                       |
[2021-04-14 03:02:18,443] [builder.py:368]            [DEBUG]    | Value: sync                                                                                        |
[2021-04-14 03:02:18,446] [config.py:509]             [INFO]     |                                                                                                    |
[2021-04-14 03:02:18,446] [config.py:511]             [INFO]     | Sync Mode: sync                                                                                    |
[2021-04-14 03:02:18,577] [builder.py:984]            [DEBUG]    |                                                                                                    |
[2021-04-14 03:02:18,577] [builder.py:985]            [DEBUG]    | Method: imdb_list                                                                                  |
[2021-04-14 03:02:18,577] [builder.py:986]            [DEBUG]    | Values: [{'url': 'https://www.imdb.com/search/title/?groups=top_250&count=250/', 'limit': 0}]      |
[2021-04-14 03:02:18,577] [builder.py:1007]           [INFO]     |                                                                                                    |
[2021-04-14 03:02:18,577] [builder.py:1008]           [DEBUG]    | Value: {'url': 'https://www.imdb.com/search/title/?groups=top_250&count=250/', 'limit': 0}         |
[2021-04-14 03:02:18,578] [imdb.py:85]                [DEBUG]    | Data: {'url': 'https://www.imdb.com/search/title/?groups=top_250&count=250/', 'limit': 0}          |
[2021-04-14 03:02:18,578] [imdb.py:97]                [INFO]     | Processing IMDb List: https://www.imdb.com/search/title/?groups=top_250&count=250/                 |
[2021-04-14 03:02:20,060] [util.py:303]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "C:\Users\hersh\Documents\Plex Meta Manager\modules\config.py", line 523, in update_libraries
                                                                 |     builder.run_methods(collection_obj, collection_name, rating_key_map, movie_map, show_map)
                                                                 |   File "C:\Users\hersh\Documents\Plex Meta Manager\modules\builder.py", line 1019, in run_methods
                                                                 |     elif "imdb" in method:                              items_found += check_map(self.config.IMDb.get_items(method, value, self.library.Plex.language))
                                                                 |   File "C:\Users\hersh\Documents\Plex Meta Manager\modules\imdb.py", line 98, in get_items
                                                                 |     imdb_ids = self.get_imdb_ids_from_url(data["url"], language, data["limit"])
                                                                 |   File "C:\Users\hersh\Documents\Plex Meta Manager\modules\imdb.py", line 76, in get_imdb_ids_from_url
                                                                 |     else:                               raise Failed(f"IMDb Error: No IMDb IDs Found at {imdb_url}")
                                                                 | modules.util.Failed: IMDb Error: No IMDb IDs Found at https://www.imdb.com/search/title/?groups=top_250&count=250/
                                                                 | 
[2021-04-14 03:02:20,060] [config.py:538]             [ERROR]    | Unknown Error: IMDb Error: No IMDb IDs Found at https://www.imdb.com/search/title/?groups=top_250&count=250/
[2021-04-14 03:02:20,061] [config.py:484]             [INFO]     | 
[2021-04-14 03:02:20,061] [util.py:349]               [INFO]     |====================================================================================================|
```

Movies.yml:
```
templates:
  List:
      optional:
        - imdb_url
        - trakt_url
      imdb_list: <<imdb_url>>
      trakt_list: <<trakt_url>>
      summary: <<summary>>
      sort_title: '/<<num>>'
      collection_order: alpha
      collection_mode: default
      sync_mode: sync

collections:
  IMDb Top 250:
      template: {name: List, imdb_url: https://www.imdb.com/search/title/?groups=top_250&count=250/, summary: "IMDB's 250 top rated movies of all time.", num: '003'}
```

**Comment by meisnate12** [comment]
change your link from:
`https://www.imdb.com/search/title/?groups=top_250&count=250/`
to
`https://www.imdb.com/search/title/?groups=top_250&count=250`

that last slash is causing it to fail

**Comment by omerher** [comment]
Fixed it!
