### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by calboi91** [Kometa-Team/Kometa#215]
I am running 1.8.0, and I get the following error:
```

[2021-04-26 09:50:04,686] [util.py:313]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "plex_meta_manager.py", line 110, in start
                                                                 |     config = Config(default_dir, config_path, libraries_to_run)
                                                                 |   File "/home9/calboi/Plex-Meta-Manager/modules/config.py", line 391, in __init__
                                                                 |     if self.general["radarr"]["url"] or "radarr" in lib:
                                                                 | TypeError: argument of type 'NoneType' is not iterable
                                                                 | 
[2021-04-26 09:50:04,687] [plex_meta_manager.py:114]  [CRITICAL] | argument of type 'NoneType' is not iterable
```
I do not have radarr configured in my config.yml file.

**Comment by meisnate12** [comment]
I think this is already fixed in develop
