### ISSUE TITLE
[Defaults]: Installation walk-thru fails with numerous errors

### ISSUE THREAD

**Issue by douginoz** [Kometa-Team/Kometa#2297]
### Link to File

default config files

### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

Long-time Kometa user; recently found log files chockers with errors so thought I'd try a clean test install to figure out any new parameters, changes, etc.  I'm following the installation page (https://metamanager.wiki/en/latest/kometa/install/local/#setting-up-the-initial-config-file) as near-as exactly, but see the same sort of errors in the log files that I see in my prod server.

Running Version: 2.1.0 (Python 3.11.6) (Git: master)
Platform: Linux-6.5.0-44-generic-x86_64-with-glibc2.38  (Ubuntu 23.10)
Plex: 1.41.1.9057-af5eaea7a

This is a fresh install of kometa, not in docker, into ~/Kometa etc.
Assume I'm following the installation instructions to the letter.  I've documented some of the steps I took but this is just going to fill up the issue report.

- created Movies_Test plex library with 10 movies in it by following the "Prepare a Small Test Library guide in https://metamanager.wiki/en/latest/kometa/install/local/#prepare-a-small-test-library-optional

- added plex url, token, tmdb api key etc.
- copied config.yml.template to config.yml
- commented out the unused libraries TV Shows, Anime, Music
- added "Movies-NOSUCHLIBRARY"
- ran kometa: python kometa.py -r
- renamed Movies-NOSUCHLIBRARY to Movies-Test
- ran kometa again: python kometa.py -r

At this point, it runs fine, but the logs show many errors, and my Movies-Test plex library does not have any Collections tab like it's supposed to, causing me to look through the logs carefully.

1. in the IMDb Top 250 Collection section, missing movies, it finds 248 movies missing, which is right since I created 2 in my test library as per the installation instructions, leavingh 248 not found.  This first error appears dozens of times in my production library, as it does here:
```
Found: IMDB Top 250                                                                                |
| Looking for: IMDb Top 250                                                                          |
| Traceback (most recent call last):                                                                 |
|   File "/home/moa/Kometa/kometa.py", line 867, in run_collection                                   |
|     builder.load_collection()                                                                      |
|   File "/home/moa/Kometa/modules/builder.py", line 3278, in load_collection                        |
|     self.obj = self.library.get_playlist(self.name) if self.playlist else self.library.get_collection(self.name, force_search=True) |
|                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
|   File "/home/moa/Kometa/modules/plex.py", line 1058, in get_collection                            |
|     raise Failed(f"Plex Error: Collection {data} not found")                                       |
| modules.util.Failed: Plex Error: Collection IMDb Top 250 not found                                 |
|                                                                                                    |
```
2.
```
|======================== Validating Arrowverse (Timeline Order) Attributes =========================|
|                                                                                                    |
| Validating Method: name                                                                            |
| Value: Arrowverse (Timeline Order)                                                                 |
| Final Name: Arrowverse (Timeline Order)                                                            |
|                                                                                                    |
| Validating Method: libraries                                                                       |
| Value: Movies, TV Shows                                                                            |
| Traceback (most recent call last):                                                                 |
|   File "/home/moa/Kometa/kometa.py", line 976, in run_playlists                                    |
|     builder = CollectionBuilder(config, playlist_file, mapping_name, playlist_attrs, extra=output_str) |
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
|   File "/home/moa/Kometa/modules/builder.py", line 413, in __init__                                |
|     raise Failed(f"Playlist Error: Library: {pl_library} not defined")                             |
| modules.util.Failed: Playlist Error: Library: Movies not defined                                   |
|                                                                                                    |
| Playlist Error: Library: Movies not defined                                                        |
|                                                                                                    |
```
This repeats:
Validating Marvel Cinematic Universe (Timeline Order) Attributes
Validating DC Animated Universe (Timeline Order) Attributes
etc.

(Why are all these even in the default config?  Is it assumed that anyone setting up Kometa is a sci-fi buff and wants all this?)

Suggestion:  Don't include these many, many collections in the defaults.  Most people don't have or likely don't want them.  They add a lot of unnecessary additional processing during the run, and will mean that anyone initially setting up Kometa will need to delete a lot of configurations, which in turn means they need to dive really deeply into understanding where all this is configured. 

Summary:
```
|                                              Summary                                               |
|====================================================================================================|
|                                                                                                    |
|======================================== MoviesTest Summary ========================================|
|                                                                                                    |
| Title                       | Run Time |                                                           |
| =========================== | ======== |                                                           |
| Library Loading and Mapping |  0:00:00 |                                                           |
| Library Operations          |  0:00:00 |                                                           |
| Library Images Files        |  0:00:00 |                                                           |
| Library Metadata Files      |  0:00:00 |                                                           |
| Library Collection Files    |  0:00:05 |                                                           |
| Library Overlay Files       |  0:00:29 |                                                           |
|                                                                                                    |
|                   Title                    |   +   |   =   |   -   | Run Time | Status             |
|============================================|=======|=======|=======|==========|====================|
| Newly Released                             |     0 |     0 |     0 |  0:00:00 | Unchanged          |
| New Episodes                               |     0 |     0 |     0 |  0:00:00 | Skipped Run Definition |
| IMDb Popular                               |     0 |     6 |     0 |  0:00:01 | Unchanged          |
| IMDb Top 250                               |     2 |     0 |     0 |  0:00:02 | Unchanged          |
| IMDb Lowest Rated                          |     0 |     2 |     0 |  0:00:01 | Unchanged          |
|                                                                                                    |
|======================================== Playlists Summary =========================================|
|                                                                                                    |
|                   Title                    |   +   |   =   |   -   | Run Time | Status             |
|============================================|=======|=======|=======|==========|====================|
| Arrowverse (Timeline Order)                |     0 |     0 |     0 |  0:00:00 | Kometa Failure     |
| Playlist Error: Library: Movies not defined                                                        |
|                                                                                                    |
| Marvel Cinematic Universe (Timeline Order) |     0 |     0 |     0 |  0:00:00 | Kometa Failure     |
| Playlist Error: Library: Movies not defined                                                        |
|                                                                                                    |
| DC Animated Universe (Timeline Order)      |     0 |     0 |     0 |  0:00:00 | Kometa Failure     |
| Playlist Error: Library: Movies not defined                                                        |
|                                                                                                    |
| Pokémon (Timeline Order)                   |     0 |     0 |     0 |  0:00:00 | Kometa Failure     |
| Playlist Error: Library: Movies not defined                                                        |
|                                                                                                    |
| Star Trek (Timeline Order)                 |     0 |     0 |     0 |  0:00:00 | Kometa Failure     |
| Playlist Error: Library: Movies not defined                                                        |
|                                                                                                    |
| Star Wars (Timeline Order)                 |     0 |     0 |     0 |  0:00:00 | Kometa Failure     |
| Playlist Error: Library: Movies not defined                                                        |
|                                                                                                    |
| Star Wars The Clone Wars (Timeline Order)  |     0 |     0 |     0 |  0:00:00 | Kometa Failure     |
| Playlist Error: Library: Movies not defined                                                        |
|                                                                                                    |
| X-Men (Timeline Order)                     |     0 |     0 |     0 |  0:00:00 | Kometa Failure     |
| Playlist Error: Library: Movies not defined                                                        |
|                                                                                                    |
| Dragon Ball (Timeline Order)               |     0 |     0 |     0 |  0:00:00 | Kometa Failure     |
| Playlist Error: Library: Movies not defined                                                        |
|                                                                                                    |
|                                                                                                    |
|====================================== Overlay Errors Summary ======================================|
|                                                                                                    |
| No Items found for 11 Overlays: ['Oscars Best Director', 'BAFTA Winners', 'Cannes Winners', 'Berlinale Winners', 'Venice Winners', 'Sundance Winners', 'Emmys Winner', 'Critics Choice Winners', 'Spirit Winners', 'Cesar Winners', 'Commonsense Selection'] |
|                                                                                                    |
|========================================= Convert Summary ==========================================|
|                                                                                                    |
| No TMDb ID Found for IMDb ID:                                                                      |
| tt0103516, tt13989524                                                                              |
| No TVDb ID Found for TMDb ID:                                                                      |
| 47101, 258850, 15560, 11389                                                                        |
|                                                                                                    |
|========================================= Warning Summary ==========================================|
|                                                                                                    |
| Count | Message                                                                                    |
|=======|============================================================================================|
|     1 | Config Error: gotify sub-attribute token is blank                                          |
|     1 | Config Error: mal sub-attribute client_id is blank                                         |
|     1 | Config Error: anidb sub-attribute client is blank                                          |
|     1 | Config Error: anidb sub-attribute username is blank                                        |
|     1 | Asset Warning: Unable to find asset folder: 'Newly Released'                               |
|     1 | Asset Warning: Unable to find asset folder: 'IMDb Popular'                                 |
|     1 | Asset Warning: Unable to find asset folder: 'IMDb Lowest Rated'                            |
|                                                                                                    |
|========================================== Error Summary ===========================================|
|                                                                                                    |
| Count | Message                                                                                    |
|=======|============================================================================================|
|     9 | Playlist Error: Library: Movies not defined                                                |
|                                                                                                    |
|====================================================================================================|
|                                            Finished Run                                            |
|                                           Version: 2.1.0                                           |
|                          Finished: 14:03:16 2024-10-23 Run Time: 0:00:39                           |
|====================================================================================================|
```

The result is that the plex library doesn't seem to have been updated at all.  There are no visible overlays nor any Collections tab.

**Comment by antwanchild** [comment]
If you could create a help thread on our discord and provide logs

**Comment by douginoz** [comment]
Thanks
