### ISSUE TITLE
Updating Show Title results in error

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#234]
This is on develop

YML
```
  "Avatar: The Legend of Korras":
    alt_title: The Legend of Korra
    original_title: The Legend of Korra
```
```
[2021-05-07 15:28:55,200] [plex.py:904]               [INFO]     |                                                                                                    |
[2021-05-07 15:28:55,234] [plex.py:932]               [INFO]     | Updating Show: Avatar: The Legend of Korras...                                                     |
[2021-05-07 15:28:55,234] [plex.py:831]               [INFO]     | Detail: title updated to Avatar: The Legend of Korras                                              |
[2021-05-07 15:28:55,573] [plex.py:792]               [DEBUG]    | Details Update: {'title.value': 'Avatar: The Legend of Korras', 'title.locked': 1}                 |
[2021-05-07 15:29:45,621] [util.py:313]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 111, in start
                                                                 |     config.update_libraries(is_test, collections_to_run, resume_from)
                                                                 |   File "/modules/config.py", line 480, in update_libraries
                                                                 |     try:                        library.update_metadata(self.TMDb, test)
                                                                 |   File "/modules/plex.py", line 990, in update_metadata
                                                                 |     self.edit_item(item, mapping_name, item_type, edits)
                                                                 |   File "/modules/plex.py", line 794, in edit_item
                                                                 |     self.edit_query(item, edits, advanced=advanced)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/retrying.py", line 49, in wrapped_f
                                                                 |     return Retrying(*dargs, **dkw).call(f, *args, **kw)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/retrying.py", line 212, in call
                                                                 |     raise attempt.get()
                                                                 |   File "/usr/local/lib/python3.9/site-packages/retrying.py", line 247, in get
                                                                 |     six.reraise(self.value[0], self.value[1], self.value[2])
                                                                 |   File "/usr/local/lib/python3.9/site-packages/six.py", line 719, in reraise
                                                                 |     raise value
                                                                 |   File "/usr/local/lib/python3.9/site-packages/retrying.py", line 200, in call
                                                                 |     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
                                                                 | TypeError: edit_query() got an unexpected keyword argument 'advanced'
                                                                 | 
[2021-05-07 15:29:45,622] [plex_meta_manager.py:114]  [CRITICAL] | edit_query() got an unexpected keyword argument 'advanced'
[2021-05-07 15:29:45,622] [plex_meta_manager.py:115]  [INFO]     | 
```

**Comment by meisnate12** [comment]
fix is in develop

**Comment by meisnate12** [comment]
also leaving open until merged
