### ISSUE TITLE
Lots of Bugs on develop with previously working configs

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#275]
I haven't been running this for awhile. So IDK exactly when it broke -- or how many things are actually broken, but it's been about 2 weeks since I've been actively running this. None of my YML configs have changed in that time.

First error:
YML:
```
metadata:
  "Avatar: The Last Airbender":
    sort_title: Avatar 01
```
Log:
```
[2021-05-25 03:50:43,052] [meta.py:196]               [INFO]     | Updating Show: Avatar: The Last Airbender...                                                       |
[2021-05-25 03:50:43,390] [meta.py:123]               [ERROR]    | Metadata Error: country attribute only works for movie libraries                                   |
[2021-05-25 03:50:43,391] [meta.py:123]               [ERROR]    | Metadata Error: director attribute only works for movie libraries                                  |
[2021-05-25 03:50:43,391] [meta.py:123]               [ERROR]    | Metadata Error: producer attribute only works for movie libraries                                  |
[2021-05-25 03:50:43,391] [meta.py:123]               [ERROR]    | Metadata Error: writer attribute only works for movie libraries                                    |
[2021-05-25 03:50:43,391] [meta.py:283]               [INFO]     | Show: Avatar: The Last Airbender Details Update Not Needed                                         |
```

Second error:
YML:
```
metadata:
  "Adam DeVine's House Party":
    genre: Stand Up
```
Log:
```
[2021-05-25 03:50:44,853] [meta.py:196]               [INFO]     | Updating Show: Adam DeVine's House Party...                                                        |
[2021-05-25 03:50:45,051] [util.py:328]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 111, in start
                                                                 |     update_libraries(config, is_test, requested_collections, resume_from)
                                                                 |   File "//plex_meta_manager.py", line 144, in update_libraries
                                                                 |     metadata.update_metadata(config.TMDb, is_test)
                                                                 |   File "/modules/meta.py", line 268, in update_metadata
                                                                 |     if edit_tags("genre", item, meta, methods, extra=genres):
                                                                 |   File "/modules/meta.py", line 143, in edit_tags
                                                                 |     return self.library.edit_tags("attr", obj, add_tags=add_tags, remove_tags=remove_tags, sync_tags=sync_tags, key=key)
                                                                 |   File "/modules/plex.py", line 693, in edit_tags
                                                                 |     item_tags = [item_tag.tag for item_tag in getattr(obj, key)]
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 428, in __getattribute__
                                                                 |     value = super(PlexPartialObject, self).__getattribute__(attr)
                                                                 | AttributeError: 'Show' object has no attribute 'attrs'
                                                                 | 
[2021-05-25 03:50:45,052] [plex_meta_manager.py:114]  [CRITICAL] | 'Show' object has no attribute 'attrs'
```

That's as far as I get now after running this, whole script only runs for about 15 seconds now before crashing from that last error.

I have a lot of stuff in that config, so there's a good chance I'll find more errors once those get fixed.

**Comment by meisnate12** [comment]
I will take a look at this now lol give me a few minutes

**Comment by meisnate12** [comment]
fix is in develop

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
lol, now this is happening
```
[2021-05-25 04:51:55,561] [meta.py:196]               [INFO]     | Updating Show: Adam DeVine's House Party...                                                        |
[2021-05-25 04:51:55,952] [plex.py:712]               [INFO]     | Detail: Genre S added                                                                              |
[2021-05-25 04:51:56,158] [plex.py:712]               [INFO]     | Detail: Genre t added                                                                              |
[2021-05-25 04:51:56,325] [plex.py:712]               [INFO]     | Detail: Genre a added                                                                              |
[2021-05-25 04:51:56,502] [plex.py:712]               [INFO]     | Detail: Genre n added                                                                              |
[2021-05-25 04:51:56,742] [plex.py:712]               [INFO]     | Detail: Genre d added                                                                              |
[2021-05-25 04:51:57,026] [plex.py:712]               [INFO]     | Detail: Genre   added                                                                              |
[2021-05-25 04:51:57,228] [plex.py:712]               [INFO]     | Detail: Genre U added                                                                              |
[2021-05-25 04:51:57,610] [plex.py:712]               [INFO]     | Detail: Genre p added     
```

**Comment by meisnate12** [comment]
ok fixed that lol anymore?

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Nah, it's still doing the individual letter genre thing.

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
I'm going to comment out my genre changes for now and see if I notice any other bugs. This one is particularly annoying because I have to stop it and remove the extra genres before it gets out of hand

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Alright, so the genre issue happens with labels as well

**Comment by meisnate12** [comment]
it definitely fixed it for me make sure your version is 1.9.3-beta1

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
I̶D̶K̶ ̶w̶h̶a̶t̶'̶s̶ ̶w̶r̶o̶n̶g̶ ̶w̶i̶t̶h̶ ̶i̶t̶ ̶o̶n̶ ̶m̶y̶ ̶e̶n̶d̶ ̶t̶h̶e̶n̶.̶.̶.̶ ̶J̶u̶s̶t̶ ̶n̶o̶w̶ ̶I̶ ̶d̶i̶d̶ ̶a̶ ̶p̶u̶l̶l̶,̶ ̶a̶n̶d̶ ̶i̶t̶ ̶s̶a̶i̶d̶ ̶i̶t̶ ̶w̶a̶s̶ ̶p̶u̶l̶l̶i̶n̶g̶ ̶n̶e̶w̶ ̶c̶o̶d̶e̶.̶ ̶I̶ ̶t̶h̶o̶u̶g̶h̶t̶ ̶t̶h̶a̶t̶ ̶w̶o̶u̶l̶d̶'̶v̶e̶ ̶f̶i̶x̶ ̶i̶t̶,̶ ̶b̶u̶t̶ ̶a̶f̶t̶e̶r̶ ̶r̶u̶n̶n̶i̶n̶g̶ ̶i̶t̶ ̶t̶h̶e̶ ̶o̶u̶t̶p̶u̶t̶ ̶s̶t̶i̶l̶l̶ ̶s̶a̶y̶s̶ ̶V̶e̶r̶s̶i̶o̶n̶ ̶1̶.̶9̶.̶2̶.̶.̶.̶

Closed my terminal and did another pull, which found another update, and now it's running 1.9.3-beta1. IDK what's up with that, seems like some sort of caching issue on my end.

Running the script again

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Seems like it's working so far. It usually takes 20-30m though, so I'll check the output tomorrow and let you know if I notice anything else.

Thanks!

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Well it doesn't seem to have broken anything along the way, but I'll just list out any errors in the log in case you wanted to handle them without throwing an error. All very minor stuff though, everything else looks good :+1: 

So if a genre doesn't exist, there's this error:
```
[2021-05-25 05:52:09,763] [util.py:328]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 431, in run_collection
                                                                 |     builder = CollectionBuilder(config, library, metadata, mapping_name, collection_attrs)
                                                                 |   File "/modules/builder.py", line 1016, in __init__
                                                                 |     searches[search_final] = self.library.validate_search_list(final_values, search)
                                                                 |   File "/modules/plex.py", line 508, in validate_search_list
                                                                 |     raise Failed(f"Plex Error: {search_name}: {value} not found")
                                                                 | modules.util.Failed: Plex Error: genre: Adventure not found
                                                                 | 
[2021-05-25 05:52:09,764] [util.py:325]               [ERROR]    | Plex Error: genre: Adventure not found
```

If a collection is missing:
```
[2021-05-25 06:09:09,271] [builder.py:672]            [DEBUG]    | Value: ordereddict([('genre', 'Animation'), ('collection.not', 'Anime')])                          |
[2021-05-25 06:09:09,444] [util.py:328]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 431, in run_collection
                                                                 |     builder = CollectionBuilder(config, library, metadata, mapping_name, collection_attrs)
                                                                 |   File "/modules/builder.py", line 1016, in __init__
                                                                 |     searches[search_final] = self.library.validate_search_list(final_values, search)
                                                                 |   File "/modules/plex.py", line 508, in validate_search_list
                                                                 |     raise Failed(f"Plex Error: {search_name}: {value} not found")
                                                                 | modules.util.Failed: Plex Error: collection: Anime not found
                                                                 | 
[2021-05-25 06:09:09,445] [util.py:325]               [ERROR]    | Plex Error: collection: Anime not found
```

If no items are found to add to a collection (this one happened because of a typo)
```
[2021-05-25 06:09:40,060] [plex.py:582]               [INFO]     | Processing Plex Search: title.begins(Silent Night Deadly Night)                                    |
[2021-05-25 06:09:40,060] [plex.py:588]               [DEBUG]    | Search: {'title<': ['Silent Night Deadly Night']}                                                  |
[2021-05-25 06:09:40,136] [util.py:328]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 451, in run_collection
                                                                 |     builder.collect_rating_keys(movie_map, show_map)
                                                                 |   File "/modules/builder.py", line 1346, in collect_rating_keys
                                                                 |     if "plex" in method:                                add_rating_keys(self.library.get_items(method, value))
                                                                 |   File "/modules/plex.py", line 632, in get_items
                                                                 |     raise Failed("Plex Error: No Items found in Plex")
                                                                 | modules.util.Failed: Plex Error: No Items found in Plex
                                                                 | 
[2021-05-25 06:09:40,137] [util.py:325]               [ERROR]    | Plex Error: No Items found in Plex
```

**Comment by meisnate12** [comment]
this first two are actually the exact same error the validation failed for the item given. I.E. there's no item in plex that has the given tag. I assume thats a user error so i error out that collection you can add `validate: false` to `plex_search` or `smart_filter` to have PMM continue ignoring tags that are not validated.

Honestly same with the last one its failing to find any items in your plex search so i assume thees a user error and error out the collection. 

I originally didn't have the traceback print but it ended up being helpful in debugging so i left it on in debug mode
