### ISSUE TITLE
Error using mass_genre_update

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#278]
Trying to implement this today. Haven't had it working before, so there could be something wrong with the config -- But from what I saw on the wiki it should be correct.

config.yml
```
libraries:
  Shows:
    mass_genre_update: tmdb
settings:
  ...
```

Log
```
[2021-05-27 01:07:14,350] [util.py:329]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 122, in start
                                                                 |     update_libraries(config)
                                                                 |   File "//plex_meta_manager.py", line 149, in update_libraries
                                                                 |     mass_metadata(config, library, movie_map, show_map)
                                                                 |   File "//plex_meta_manager.py", line 289, in mass_metadata
                                                                 |     t_id, guid_media_type, _ = config.Cache.config.Cache.query_guid_map(item.guid)
                                                                 | AttributeError: 'Cache' object has no attribute 'config'
                                                                 | 
[2021-05-27 01:07:14,351] [plex_meta_manager.py:125]  [CRITICAL] | 'Cache' object has no attribute 'config'
[2021-05-27 01:07:14,357] [plex_meta_manager.py:126]  [INFO]     | 
```

**Comment by meisnate12** [comment]
fix is in develop
