### ISSUE TITLE
Working Genre Collections for Shows break in Movie Libraries

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#279]
config
```
  "Anime":
    sort_title: +Anime
    collection_mode: hide_items
    collection_order: alpha
    genre: Anime
```

log
```
[2021-05-27 23:26:07,065] [plex.py:584]               [INFO]     | Processing Plex Search: genre(Anime)                                                               |
[2021-05-27 23:26:07,065] [plex.py:590]               [DEBUG]    | Search: {'genre': ['Anime']}                                                                       |
[2021-05-27 23:26:07,213] [plex_meta_manager.py:430]  [INFO]     |                                                                                                    |
[2021-05-27 23:26:07,214] [util.py:374]               [INFO]     |==================================== Adding to Anime Collection ====================================|
[2021-05-27 23:26:07,214] [plex_meta_manager.py:432]  [INFO]     |                                                                                                    |
[2021-05-27 23:26:07,247] [util.py:323]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 433, in run_collection
                                                                 |     builder.add_to_collection()
                                                                 |   File "/modules/builder.py", line 1387, in add_to_collection
                                                                 |     logger.info(util.adjust_space(f"{name} Collection | {'=' if current in collection_items else '+'} | {current.title}"))
                                                                 | AttributeError: 'NoneType' object has no attribute 'title'
                                                                 | 
[2021-05-27 23:26:07,248] [plex_meta_manager.py:462]  [ERROR]    | Unknown Error: 'NoneType' object has no attribute 'title'
[2021-05-27 23:26:07,248] [plex_meta_manager.py:463]  [INFO]     | 
[2021-05-27 23:26:07,248] [util.py:370]               [INFO]     |====================================================================================================|
[2021-05-27 23:26:07,248] [util.py:374]               [INFO]     |                                     Finished Anime Collection                                      |
[2021-05-27 23:26:07,248] [util.py:374]               [INFO]     |                                    Collection Run Time: 0:00:00                                    |
[2021-05-27 23:26:07,248] [util.py:378]               [INFO]     |====================================================================================================|
```

**Comment by meisnate12** [comment]
this has been fixed but docker is currently having trouble building containers so it cant update

**Comment by meisnate12** [comment]
actually docker has finally built the container so update to the latest develop and let me know if your still having the issue

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Looks like it's working :+1:
