### ISSUE TITLE
TV Shows error - invalid literal for int() with base 10: 'None'  

### ISSUE THREAD

**Issue by Tharic99** [Kometa-Team/Kometa#292]
My TV Shows library has had a problem for a few weeks, but I didn't realize it. 

```
|                                                                                                    |
|====================================================================================================|
|                                          TV Shows Library                                          |
|====================================================================================================|
|                                                                                                    |
|===================================== Mapping TV Shows Library =====================================|
|                                                                                                    |
| Loading Show Library: TV Shows                                                                     |
|                                                                                                    |
| Mapping Show Library: TV Shows                                                                     |
|                                                                                                    |
| Mapping Error | plex://show/5d9c09004eefaa001f5e6762           | Unable to convert IMDb ID: tt12110402 to TMDb ID for Helen Mirren Teaches Acting |
| invalid literal for int() with base 10: 'None'                                                     |
|                                                                                                    |
|====================================================================================================|
|                                       Finished Libraries Run                                       |
|                                         Run Time: 0:00:03                                          |
|====================================================================================================|
```

Any ideas what I'm missing?

**Comment by meisnate12** [comment]
what version are you using? and can you send me the traceback in the meta.log file

**Comment by Tharic99** [comment]
1.10

```
[2021-06-04 22:29:07,246] [plex.py:610]               [INFO]     | Mapping Show Library: TV Shows                                                                     |
[2021-06-04 22:29:07,247] [plex.py:611]               [INFO]     |                                                                                                    |
[2021-06-04 22:29:07,617] [convert.py:362]            [INFO]     | Mapping Error | plex://show/5d9c09004eefaa001f5e6762           | Unable to convert IMDb ID: tt12110402 to TMDb ID for Helen Mirren Teaches Acting |
[2021-06-04 22:29:07,629] [util.py:323]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 122, in start
                                                                 |     update_libraries(config)
                                                                 |   File "//plex_meta_manager.py", line 147, in update_libraries
                                                                 |     library.map_guids(config)
                                                                 |   File "/modules/plex.py", line 615, in map_guids
                                                                 |     id_type, main_id = config.Convert.get_id(item, self)
                                                                 |   File "/modules/convert.py", line 257, in get_id
                                                                 |     return media_id_type, util.get_list(cache_id, int_list=True)
                                                                 |   File "/modules/util.py", line 224, in get_list
                                                                 |     elif int_list is True:          return [int(d.strip()) for d in str(data).split(",")]
                                                                 |   File "/modules/util.py", line 224, in <listcomp>
                                                                 |     elif int_list is True:          return [int(d.strip()) for d in str(data).split(",")]
                                                                 | ValueError: invalid literal for int() with base 10: 'None'
                                                                 | 
[2021-06-04 22:29:07,633] [plex_meta_manager.py:125]  [CRITICAL] | invalid literal for int() with base 10: 'None'
[2021-06-04 22:29:07,633] [plex_meta_manager.py:126]  [INFO]     | 
[2021-06-04 22:29:07,634] [util.py:370]               [INFO]     |====================================================================================================|
[2021-06-04 22:29:07,634] [util.py:374]               [INFO]     |                                       Finished Libraries Run                                       |
[2021-06-04 22:29:07,634] [util.py:374]               [INFO]     |                                         Run Time: 0:00:03                                          |
[2021-06-04 22:29:07,635] [util.py:378]               [INFO]     |====================================================================================================|

```

**Comment by meisnate12** [comment]
can you try using a brand new cache file

**Comment by Tharic99** [comment]
That fixed it.. thanks!
