### ISSUE TITLE
Feature Request: Add folder support for metadata_path config

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#360]
Discussion here: https://github.com/meisnate12/Plex-Meta-Manager/discussions/357

**Comment by meisnate12** [comment]
its already added to develop lol

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Having some issues getting this working. I set the folder path the same way it was setup for my `asset_directory:` path

I wasn't sure if it would automatically dig through subdirectories or not (it would be cool if it could). The file I'm trying to access is at config/shows/quickfixes/______.yml

**config.yml**
```
libraries:
  Shows:
    metadata_path:
      - folder: config/shows
```
**meta.log**
```
[2021-08-14 01:39:52,575] [plex_meta_manager.py:111]  [INFO]     |           Version: 1.11.3-beta5                                                                    |
[2021-08-14 01:39:52,575] [util.py:184]               [INFO]     |====================================================================================================|
[2021-08-14 01:39:54,804] [config.py:339]             [INFO]     | Connecting to Shows Library...                                                                     |
[2021-08-14 01:39:54,833] [meta.py:19]                [INFO]     | Loading Metadata Folder: config/shows                                                              |
[2021-08-14 01:39:54,834] [util.py:137]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/meta.py", line 47, in __init__
                                                                 |     content = open(path, encoding="utf-8")
                                                                 | IsADirectoryError: [Errno 21] Is a directory: 'config/shows'
                                                                 | 
[2021-08-14 01:39:54,834] [plex.py:265]               [ERROR]    | YAML Error: [Errno 21] Is a directory: 'config/shows'
[2021-08-14 01:39:54,834] [plex.py:268]               [INFO]     | 
[2021-08-14 01:39:54,835] [util.py:137]               [DEBUG]    | Traceback (most recent call last):
                                                                 |   File "/modules/config.py", line 410, in __init__
                                                                 |     library = Plex(self, params)
                                                                 |   File "/modules/plex.py", line 269, in __init__
                                                                 |     raise Failed("Metadata File Error: No valid metadata files found")
                                                                 | modules.util.Failed: Metadata File Error: No valid metadata files found
                                                                 | 
[2021-08-14 01:39:54,835] [util.py:134]               [ERROR]    | Metadata File Error: No valid metadata files found
[2021-08-14 01:39:54,835] [config.py:416]             [INFO]     | Shows Library Connection Failed
[2021-08-14 01:39:54,835] [util.py:184]               [INFO]     |====================================================================================================|
[2021-08-14 01:39:54,836] [util.py:137]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 122, in start
                                                                 |     config = Config(default_dir, config_path=config_path, is_test=is_test,
                                                                 |   File "/modules/config.py", line 495, in __init__
                                                                 |     raise Failed("Plex Error: No Plex libraries were connected to")
                                                                 | modules.util.Failed: Plex Error: No Plex libraries were connected to
                                                                 | 
[2021-08-14 01:39:54,836] [plex_meta_manager.py:128]  [CRITICAL] | Plex Error: No Plex libraries were connected to
[2021-08-14 01:39:54,836] [plex_meta_manager.py:129]  [INFO]     | 
[2021-08-14 01:39:54,836] [util.py:184]               [INFO]     |====================================================================================================|
[2021-08-14 01:39:54,836] [util.py:188]               [INFO]     |                                            Finished Run                                            |
[2021-08-14 01:39:54,836] [util.py:188]               [INFO]     |                                         Run Time: 0:00:02                                          |
[2021-08-14 01:39:54,836] [util.py:192]               [INFO]     |====================================================================================================|
```

And here's my second attempt:
**config.yml**
```
libraries:
  Shows:
    metadata_path:
      - folder: config/shows/quickfixes
```
**meta.log**
```
[2021-08-14 01:45:35,297] [plex_meta_manager.py:111]  [INFO]     |           Version: 1.11.3-beta5                                                                    |
[2021-08-14 01:45:35,297] [util.py:184]               [INFO]     |====================================================================================================|
[2021-08-14 01:45:37,971] [config.py:339]             [INFO]     | Connecting to Shows Library...                                                                     |
[2021-08-14 01:45:37,994] [meta.py:19]                [INFO]     | Loading Metadata Folder: config/shows/quickfixes                                                   |
[2021-08-14 01:45:37,995] [util.py:137]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/meta.py", line 47, in __init__
                                                                 |     content = open(path, encoding="utf-8")
                                                                 | IsADirectoryError: [Errno 21] Is a directory: 'config/shows/quickfixes'
                                                                 | 
[2021-08-14 01:45:37,995] [plex.py:265]               [ERROR]    | YAML Error: [Errno 21] Is a directory: 'config/shows/quickfixes'
[2021-08-14 01:45:37,995] [plex.py:268]               [INFO]     | 
[2021-08-14 01:45:37,996] [util.py:137]               [DEBUG]    | Traceback (most recent call last):
                                                                 |   File "/modules/config.py", line 410, in __init__
                                                                 |     library = Plex(self, params)
                                                                 |   File "/modules/plex.py", line 269, in __init__
                                                                 |     raise Failed("Metadata File Error: No valid metadata files found")
                                                                 | modules.util.Failed: Metadata File Error: No valid metadata files found
                                                                 | 
[2021-08-14 01:45:37,996] [util.py:134]               [ERROR]    | Metadata File Error: No valid metadata files found
[2021-08-14 01:45:37,996] [config.py:416]             [INFO]     | Shows Library Connection Failed
[2021-08-14 01:45:37,996] [util.py:184]               [INFO]     |====================================================================================================|
[2021-08-14 01:45:37,996] [util.py:137]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 122, in start
                                                                 |     config = Config(default_dir, config_path=config_path, is_test=is_test,
                                                                 |   File "/modules/config.py", line 495, in __init__
                                                                 |     raise Failed("Plex Error: No Plex libraries were connected to")
                                                                 | modules.util.Failed: Plex Error: No Plex libraries were connected to
                                                                 | 
[2021-08-14 01:45:37,996] [plex_meta_manager.py:128]  [CRITICAL] | Plex Error: No Plex libraries were connected to
[2021-08-14 01:45:37,997] [plex_meta_manager.py:129]  [INFO]     | 
[2021-08-14 01:45:37,997] [util.py:184]               [INFO]     |====================================================================================================|
[2021-08-14 01:45:37,997] [util.py:188]               [INFO]     |                                            Finished Run                                            |
[2021-08-14 01:45:37,997] [util.py:188]               [INFO]     |                                         Run Time: 0:00:02                                          |
[2021-08-14 01:45:37,997] [util.py:192]               [INFO]     |====================================================================================================|
```

I also tried changing `- folder:` to `- directory:` based on the error message. That just said this, which made me think that wasn't the issue.
```
| Metadata File Error: No valid metadata files found                                                 |
```

**Comment by meisnate12** [comment]
should have this fixed
