### ISSUE TITLE
Bug: Anilist search 'Unknown Error' line 105 in anilist.py  - 'list' object has no attribute 'lower'

### ISSUE THREAD

**Issue by mtikoian** [Kometa-Team/Kometa#369]
**Describe the Bug**
Anilist search 'Unknown Error' line 105 in anilist.py  - 'list' object has no attribute 'lower'.

**Relevant Collection Config**
- See below

**Plex Meta Manager Info**
- Version Number:  1.12.1

**Link to logs (required)**
[2021-08-24 14:57:59,198] [util.py:191]               [INFO]     |====================================================================================================|
[2021-08-24 14:57:59,203] [util.py:195]               [INFO]     |                                         Action Collection                                          |
[2021-08-24 14:57:59,204] [util.py:199]               [INFO]     |====================================================================================================|
[2021-08-24 14:57:59,205] [plex_meta_manager.py:463]  [INFO]     |                                                                                                    |
[2021-08-24 14:57:59,206] [util.py:195]               [INFO]     |=================================== Validating Action Attributes ===================================|
[2021-08-24 14:57:59,207] [builder.py:196]            [DEBUG]    |                                                                                                    |
[2021-08-24 14:57:59,208] [builder.py:197]            [DEBUG]    | Validating Method: template                                                                        |
[2021-08-24 14:57:59,209] [builder.py:203]            [DEBUG]    | Value: ordereddict([('name', 'anime'), ('num', 1)])                                                |
[2021-08-24 14:57:59,210] [builder.py:399]            [DEBUG]    |                                                                                                    |
[2021-08-24 14:57:59,211] [builder.py:400]            [DEBUG]    | Validating Method: sync_mode                                                                       |
[2021-08-24 14:57:59,211] [builder.py:404]            [DEBUG]    | Value: sync                                                                                        |
[2021-08-24 14:57:59,212] [builder.py:517]            [DEBUG]    |                                                                                                    |
[2021-08-24 14:57:59,212] [builder.py:518]            [DEBUG]    | Validating Method: anilist_search                                                                  |
[2021-08-24 14:57:59,213] [builder.py:519]            [DEBUG]    | Value: ordereddict([('genre', 'Action'), ('limit', 250)])                                          |
[2021-08-24 14:57:59,214] [util.py:353]               [WARNING]  | Collection Warning: anilist_search sort_by attribute not found using score as default              |
[2021-08-24 14:57:59,214] [builder.py:517]            [DEBUG]    |                                                                                                    |
[2021-08-24 14:57:59,215] [builder.py:518]            [DEBUG]    | Validating Method: summary                                                                         |
[2021-08-24 14:57:59,216] [builder.py:519]            [DEBUG]    | Value: Most popular Action                                                                         |
[2021-08-24 14:57:59,216] [builder.py:517]            [DEBUG]    |                                                                                                    |
[2021-08-24 14:57:59,217] [builder.py:518]            [DEBUG]    | Validating Method: file_poster                                                                     |
[2021-08-24 14:57:59,217] [builder.py:519]            [DEBUG]    | Value: config/images/Anime/action.png                                                              |
[2021-08-24 14:57:59,220] [builder.py:517]            [DEBUG]    |                                                                                                    |
[2021-08-24 14:57:59,221] [builder.py:518]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2021-08-24 14:57:59,222] [builder.py:519]            [DEBUG]    | Value: +1_1Action                                                                                  |
[2021-08-24 14:57:59,364] [builder.py:612]            [INFO]     |                                                                                                    |
[2021-08-24 14:57:59,365] [builder.py:613]            [INFO]     | Validation Successful                                                                              |
[2021-08-24 14:57:59,365] [plex_meta_manager.py:471]  [INFO]     |                                                                                                    |
[2021-08-24 14:57:59,366] [util.py:195]               [INFO]     |==================================== Building Action Collection ====================================|
[2021-08-24 14:57:59,367] [plex_meta_manager.py:483]  [INFO]     |                                                                                                    |
[2021-08-24 14:57:59,368] [plex_meta_manager.py:484]  [INFO]     | Sync Mode: sync                                                                                    |
[2021-08-24 14:57:59,368] [builder.py:1062]           [DEBUG]    |                                                                                                    |
[2021-08-24 14:57:59,369] [builder.py:1063]           [DEBUG]    | Builder: anilist_search: {'genre': ['Action'], 'sort_by': 'score', 'limit': 250}                   |
[2021-08-24 14:57:59,369] [builder.py:1064]           [INFO]     |                                                                                                    |
[2021-08-24 14:57:59,370] [util.py:144]               [DEBUG]    | Processing AniList Search:                                                                         |
                                                                 | Sort By: Average Score
                                                                 | Limit: 250
                                                                 | Genre is ['Action']
                                                                 | Sort By is score
                                                                 | Limit is 250
[2021-08-24 14:57:59,372] [util.py:144]               [DEBUG]    | Traceback (most recent call last):
                                                                 |   File "//plex_meta_manager.py", line 491, in run_collection
                                                                 |     builder.find_rating_keys()
                                                                 |   File "/modules/builder.py", line 1073, in find_rating_keys
                                                                 |     anilist_ids = self.config.AniList.get_anilist_ids(method, value)
                                                                 |   File "/modules/anilist.py", line 230, in get_anilist_ids
                                                                 |     anilist_ids = self._search(**data)
                                                                 |   File "/modules/anilist.py", line 105, in _search
                                                                 |     value = self.options[attr.replace("_", " ").title()][value.lower().replace(" / ", "-").replace(" ", "-")]
                                                                 | AttributeError: 'list' object has no attribute 'lower'
                                                                 | 
[2021-08-24 14:57:59,377] [plex_meta_manager.py:530]  [ERROR]    | Unknown Error: 'list' object has no attribute 'lower'
[2021-08-24 14:57:59,377] [plex_meta_manager.py:531]  [INFO]     | 
[2021-08-24 14:57:59,378] [util.py:191]               [INFO]     |====================================================================================================|
[2021-08-24 14:57:59,379] [util.py:195]               [INFO]     |                                     Finished Action Collection                                     |
[2021-08-24 14:57:59,379] [util.py:195]               [INFO]     |                                    Collection Run Time: 0:00:00                                    |

**Comment by meisnate12** [comment]
fix is in develop
