### ISSUE TITLE
Bug: "genre_in" requires type String

### ISSUE THREAD

**Issue by danqbudz** [Kometa-Team/Kometa#382]
**Describe the Bug**
`genre_in` entries in `anilist_search` query are unquoted.

**Relevant Collection Config**
```
anilist_search:
  genre: Action
  limit: 100
  format: movie
  sort_by: popular
```

**Plex Meta Manager Info**
- 1.12.1

**Logs**
```
[DEBUG]    | Processing AniList Search:                                                                         |
           |     Sort By Popularity
           |     Limit to 100 Anime
           |     Genre is ['Action']
           |     Format is ['movie']
[DEBUG]    | query ($page: Int) {Page(page: $page){pageInfo {hasNextPage}media(sort: POPULARITY_DESC, type: ANIME, genre_in: [Action], format_in: [MOVIE]){id}}}
[DEBUG]    | Traceback (most recent call last):
           |   File "//plex_meta_manager.py", line 491, in run_collection
           |     builder.find_rating_keys()
           |   File "/modules/builder.py", line 1074, in find_rating_keys
           |     anilist_ids = self.config.AniList.get_anilist_ids(method, value)
           |   File "/modules/anilist.py", line 251, in get_anilist_ids
           |     anilist_ids = self._search(**data)
           |   File "/modules/anilist.py", line 133, in _search
           |     return self._pagenation(query, limit=kwargs["limit"], variables=variables)
           |   File "/modules/anilist.py", line 96, in _pagenation
           |     json_obj = self._request(query, variables)
           |   File "/modules/anilist.py", line 74, in _request
           |     raise Failed(f"AniList Error: {json_obj['errors'][0]['message']}")
           | modules.util.Failed: AniList Error: Field "media" argument "genre_in" requires type String, found Action.
           | 
[ERROR]    | AniList Error: Field "media" argument "genre_in" requires type String, found Action.
```

**Comment by cpt-kuesel** [comment]
Start of the Discord Discussion:

https://discord.com/channels/822460010649878528/827036803441623100/884685849378320484

**Comment by meisnate12** [comment]
fix is in develop
