### ISSUE TITLE
Bug: TV Shows audio_language not found

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#383]
**Describe the Bug**
Using plex_search to filter audio_languages, and it errors out saying the language isn't found. Creating the same filter in the Plex Web UI works as expected

**Relevant Collection Config**
```
collections:
  "Anime":
    item_label: Anime
    genre: Anime
    plex_search:
      any:
        label: Anime
        all:
          genre: Animation
          any:
            audio_language:
              - Japanese
              - Chinese
```

**Plex Meta Manager Info**
Version: 1.12.1

**Link to logs (required)**
```
[2021-09-07 18:59:55,706] [builder.py:518]            [DEBUG]    | Validating Method: plex_search                                                                     |
[2021-09-07 18:59:55,706] [builder.py:519]            [DEBUG]    | Value: ordereddict([('any', ordereddict([('label', 'Anime'), ('all', ordereddict([('genre', 'Animation'), ('any', ordereddict([('audio_language', ['Japanese', 'Chinese'])]))]))]))]) |
[2021-09-07 18:59:55,799] [util.py:144]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 470, in run_collection
                                                                 |     builder = CollectionBuilder(config, library, metadata, mapping_name, no_missing, collection_attrs)
                                                                 |   File "/modules/builder.py", line 549, in __init__
                                                                 |     elif method_name in plex.builders or method_final in plex.searches:         self._plex(method_name, method_data)
                                                                 |   File "/modules/builder.py", line 903, in _plex
                                                                 |     new_dictionary = self.build_filter("plex_search", dict_data, type_override=type_override)
                                                                 |   File "/modules/builder.py", line 1342, in build_filter
                                                                 |     built_filter, filter_text = _filter(base_dict, is_all=base_all)
                                                                 |   File "/modules/builder.py", line 1287, in _filter
                                                                 |     inside_filter, inside_display = _filter(dict_data, is_all=attr == "all", level=level)
                                                                 |   File "/modules/builder.py", line 1287, in _filter
                                                                 |     inside_filter, inside_display = _filter(dict_data, is_all=attr == "all", level=level)
                                                                 |   File "/modules/builder.py", line 1292, in _filter
                                                                 |     validation = self.validate_attribute(attr, modifier, final_attr, _data, validate, pairs=True)
                                                                 |   File "/modules/builder.py", line 1405, in validate_attribute
                                                                 |     raise Failed(error)
                                                                 | modules.util.Failed: Plex Error: audio_language: Japanese not found
                                                                 | 
[2021-09-07 18:59:55,800] [util.py:141]               [ERROR]    | Plex Error: audio_language: Japanese not found
```
![image](https://user-images.githubusercontent.com/38122413/132397829-bf9f397c-8e43-4798-ae84-ee5ce78322a1.png)

**Comment by meisnate12** [comment]
in the plex UI do you have more then one Japanese option i know in my library i have three `Japanese`, `japanese`, and `[jap]japanese`

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
I have `Japanese` and `jap`. But it looks like only 1 show is listed as `jap`, so I'll change that to `Japanese` later.

`Japanese` is definitely correct, capitalization and spelling is the same as what I use in the Plex Web UI

**Comment by meisnate12** [comment]
Can you send me the url of your advance search from plex

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
```
&key=%2Flibrary%2Fsections%2F33%2Fall%3Ftype%3D2%26sort%3DtitleSort%26push%3D1%26push%3D1%26push%3D1%26episode.audioLanguage%3Dja%26or%3D1%26episode.audioLanguage%3Dzh%26pop%3D1%26and%3D1%26show.genre%3D4484%26pop%3D1%26or%3D1%26show.label%3D1062041%26pop%3D1&advancedFilters=1
```

**Comment by cpt-kuesel** [comment]
hey try switching to ISO-639-2 language codes. they are 2 letters and they are working very reliable for me.
for your example use "zh" for chinese and "ja" for japanese.

https://www.loc.gov/standards/iso639-2/php/code_list.php
