### ISSUE TITLE
[Bug] - Collection - tautulli - doesn't respect sort_title:

### ISSUE THREAD

**Issue by datdamnzotz** [Kometa-Team/Kometa#46]
Version: 1.1.0 
Windows 10
Python: Python 3.8.7

Using the config:
```  Plex Popular:
    tautulli_popular:
      list_days: 30
      list_size: 20
      list_buffer: 20
    tautulli_watched:
      list_days: 30
      list_size: 20
      list_buffer: 20
    schedule: daily
    sort_title: +++++_1Plex Popular
    sync_mode: sync
    summary: Movies Popular on Plex
    collection_order: alpha
```

Appears that the Collection is NOT respecting sort_title
It inserts the `Plex Popular` instead of `+++++_1Plex Popular` which is used in the conf file.

![image](https://user-images.githubusercontent.com/3913859/108285022-826f1e80-7143-11eb-9f3e-7a21b0403e03.png)

There is also an error in the console - even though the collection appears to be created and other functions are working correctly.

![image](https://user-images.githubusercontent.com/3913859/108285193-d8dc5d00-7143-11eb-8575-c01d764e3daf.png)

[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/5999399/meta.log)

**Comment by Tharic99** [comment]
If you delete the collection in Plex and then let PMM create it fresh, does it get created correctly? I feel like I had this issue with either PMM or PAC at first and had to do that myself.

**Comment by datdamnzotz** [comment]
> If you delete the collection in Plex and then let PMM create it fresh, does it get created correctly? I feel like I had this issue with either PMM or PAC at first and had to do that myself.

It creates it wrong the first time - and doesn't update it on sequential runs.

**Comment by meisnate12** [comment]
is sort_title being respected for your other collections?

**Comment by meisnate12** [comment]
and can you post your meta.log

**Comment by meisnate12** [comment]
the Unknown Error is because that item no longer exists on plex or no longer exists on plex under that ratingKey

**Comment by datdamnzotz** [comment]
> is sort_title being respected for your other collections?

Yes it is.

```
  IMdb Popular:
    tmdb_popular: 40
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=feature,tv_movie,documentary,short
      limit: 40
    sort_title: +++++_4Popular
    sync_mode: sync
    summary: Popular Movies across the internet
```

![image](https://user-images.githubusercontent.com/3913859/108415330-a33e7f00-71ea-11eb-8b86-381cfe4f7e16.png)

> and can you post your meta.log

It is in the original bug form.

**Comment by meisnate12** [comment]
so I'm going to be honest I'm not sure but something I'm working on might fix this, which is also way its going to be hard to test this until i finish, so once 1.2.0 is released i want to revisit this issue if its still occurring

**Comment by datdamnzotz** [comment]
Looks like one of my movies has a bad ratingKey and causing an issue with error handling.

After stepping through the code looks like it loops [through this section](https://github.com/meisnate12/Plex-Meta-Manager/blob/f25a13982d350d09ef18ec55dc93487676f5651a/modules/config.py#L960) of the code and does the library.add_to_collection for the first 3 movies just fine.  

Hitting the 4th movie it errors out with:
```
[2021-02-18 14:44:58,504] [util.py:578]               [DEBUG]    | Traceback (most recent call last):
                                                                 |   File "c:\MyProjects\Plex-Meta-Manager\modules\plex.py", line 175, in add_to_collection
                                                                 |     current = self.fetchItem(item.ratingKey if isinstance(item, (Movie, Show)) else int(item))
                                                                 |   File "c:\python38\lib\site-packages\retrying.py", line 49, in wrapped_f
                                                                 |     return Retrying(*dargs, **dkw).call(f, *args, **kw)
                                                                 |   File "c:\python38\lib\site-packages\retrying.py", line 212, in call
                                                                 |     raise attempt.get()
                                                                 |   File "c:\python38\lib\site-packages\retrying.py", line 247, in get
                                                                 |     six.reraise(self.value[0], self.value[1], self.value[2])
                                                                 |   File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\six.py", line 703, in reraise
                                                                 |     raise value
                                                                 |   File "c:\python38\lib\site-packages\retrying.py", line 200, in call
                                                                 |     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
                                                                 |   File "c:\MyProjects\Plex-Meta-Manager\modules\plex.py", line 95, in fetchItem
                                                                 |     return self.PlexServer.fetchItem(data)
                                                                 |   File "c:\python38\lib\site-packages\plexapi\base.py", line 175, in fetchItem
                                                                 |     for elem in self._server.query(ekey):
                                                                 |   File "c:\python38\lib\site-packages\plexapi\server.py", line 504, in query
                                                                 |     raise NotFound(message)
                                                                 | plexapi.exceptions.NotFound: (404) not_found; http://plex:32400/library/metadata/205685 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
```

The error is occurring here:

https://github.com/meisnate12/Plex-Meta-Manager/blob/f25a13982d350d09ef18ec55dc93487676f5651a/modules/plex.py#L173-L174

**raise Failed** causes it to drop out of the main processing loop - which never updates the sort found later on here:

https://github.com/meisnate12/Plex-Meta-Manager/blob/f25a13982d350d09ef18ec55dc93487676f5651a/modules/config.py#L1017-L1026

Changing
https://github.com/meisnate12/Plex-Meta-Manager/blob/f25a13982d350d09ef18ec55dc93487676f5651a/modules/plex.py#L173-L174
to
```
            try:                                        
                current = self.fetchItem(item.ratingKey if isinstance(item, (Movie, Show)) else int(item))
            except Exception as e:
                        util.print_stacktrace()
                        logger.error("Unknown Error: {}".format(e))
```
catches the error and allows the process to continue in the main loop.

Behavior observed after above change:

```
| Processing Tautulli Most Popular: 20 Movies                                                        |
| Plex Popular Collection | + | Movie 1                                                        |
| Plex Popular Collection | + | Movie 2                                                        |
| Plex Popular Collection | + | Movie 3                                                        |
| Plex Popular Collection | + | Movie 4                                                       |
| Unknown Error: (404) not_found; http://plex:32400/library/metadata/205685 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html> |
| Plex Popular Collection | + | Movie 4                                                       |
| 5 Movies Processed                                                                                 |
|                                                                                                    |
| Processing Tautulli Most Watched: 20 Movies                                                        |
| Plex Popular Collection | + | Movie 1                                                        |
| Plex Popular Collection | + | Movie 2                                                        |
| Plex Popular Collection | + | Movie 3                                                        |
| Plex Popular Collection | + | Movie 4                                                       |
| Unknown Error: (404) not_found; http://plex:32400/library/metadata/205685 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html> |
| Plex Popular Collection | + | Movie 4                                                       |
| 5 Movies Processed                                                                                 |
|                                                                                                    |
| 0 Movie Removed                                                                                    |
|                                                                                                    |
| Details: have been updated  

```

**Comment by meisnate12** [comment]
can you test this on the develop branch and see if the error is still occurring and see if you can update your sort title

**Comment by meisnate12** [comment]
are you still having these problems with version 1.2.2?

**Comment by datdamnzotz** [comment]
Just loaded 1.2.2 seems to work ok.
I think the whole error was due to tautulli having a wrong IDs, I did a reinstall of plex recently and I think tautulli still had old ID's for movies.  After dumping the history in tautulli I haven't seen any errors since.

**Comment by meisnate12** [comment]
awesome just let me know if you run into any more
