### ISSUE TITLE
TV mapping fails: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by doctarrwho** [Kometa-Team/Kometa#48]
Using `develop` branch, TV show library failed to map.

```
[2021-02-18 23:13:38,258] [util.py:629]               [INFO]     |====================================================================================================|
[2021-02-18 23:13:38,258] [util.py:631]               [INFO]     |                                      Mapping TV Shows Library                                      |
[2021-02-18 23:13:38,258] [util.py:632]               [INFO]     |====================================================================================================|
[2021-02-18 23:13:38,258] [config.py:441]             [INFO]     |                                                                                                    |
[2021-02-18 23:13:38,259] [config.py:1140]            [INFO]     | Mapping Show Library: TV Shows                                                                     |
[2021-02-18 23:14:30,205] [util.py:586]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "plex_meta_manager.py", line 76, in start
                                                                 |     config.update_libraries(test, collections)
                                                                 |   File "/mnt/c/repos/unraid/Plex-Meta-Manager/modules/config.py", line 442, in update_libraries
                                                                 |     movie_map, show_map = self.map_guids(library)
                                                                 |   File "/mnt/c/repos/unraid/Plex-Meta-Manager/modules/config.py", line 1145, in map_guids
                                                                 |     id_type, main_id = self.get_id(item, library, length)
                                                                 |   File "/mnt/c/repos/unraid/Plex-Meta-Manager/modules/config.py", line 1238, in get_id
                                                                 |     try:                                            tmdb_id = self.Trakt.convert_tvdb_to_tmdb(tvdb_id)
                                                                 |   File "/mnt/c/repos/unraid/Plex-Meta-Manager/modules/trakt.py", line 83, in convert_tvdb_to_tmdb
                                                                 |     def convert_tvdb_to_tmdb(self, tvdb_id):                        return self.convert_id(tvdb_id, "tvdb", "tmdb", "show")
                                                                 |   File "/home/user/.local/lib/python3.8/site-packages/retrying.py", line 49, in wrapped_f
                                                                 |     return Retrying(*dargs, **dkw).call(f, *args, **kw)
                                                                 |   File "/home/user/.local/lib/python3.8/site-packages/retrying.py", line 212, in call
                                                                 |     raise attempt.get()
                                                                 |   File "/home/user/.local/lib/python3.8/site-packages/retrying.py", line 247, in get
                                                                 |     six.reraise(self.value[0], self.value[1], self.value[2])
                                                                 |   File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
                                                                 |     raise value
                                                                 |   File "/home/user/.local/lib/python3.8/site-packages/retrying.py", line 200, in call
                                                                 |     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
                                                                 |   File "/mnt/c/repos/unraid/Plex-Meta-Manager/modules/trakt.py", line 92, in convert_id
                                                                 |     return lookup.get_key(to_source) if to_source == "imdb" else int(lookup.get_key(to_source))
                                                                 | TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
                                                                 | 
[2021-02-18 23:14:30,211] [plex_meta_manager.py:79]   [CRITICAL] | int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by doctarrwho** [comment]
Added a log entry in trakt.py, the TVDB ID of the show where this fails is [333831](https://www.thetvdb.com/series/face-off-game-face). lookup.get_key(to_source) for this show returns `None` explaining why int() throws the exception. Trakt shows that this show doesn't have a TMDB ID... which is true. This show is listed on [TMDB](https://www.themoviedb.org/tv/73381-face-off-game-face), but it looks like trakt doesn't have the TMDB ID.

**Comment by doctarrwho** [comment]
This skips this show and moves on...

```python
            try:
                id = lookup.get_key(to_source) if to_source == "imdb" else int(lookup.get_key(to_source))
            except TypeError as e:
                id = None
                logger.error("Failed to convert {} from {} to {}: {}".format(external_id, from_source, to_source, e))
            return id
```

**Comment by meisnate12** [comment]
fix should be in develop
