### ISSUE TITLE
Bug: YAML Error: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by andrewlef** [Kometa-Team/Kometa#491]
**Describe the Bug**
PMM gives "YAML Error: 'NoneType' object is not iterable" error on run.  Unable to successfully run now.

**Relevant Collection Config**
N/A.

**Plex Meta Manager Info**
1.13.2

**Link to logs (required)**

```
[2021-12-08 18:43:57,949] [util.py:199]               [INFO]     |======================================================================================================================================================|
[2021-12-08 18:43:57,949] [plex_meta_manager.py:123]  [INFO]     |                                                                                                                                                      |
[2021-12-08 18:43:57,950] [plex_meta_manager.py:124]  [INFO]     |                                 ____  _             __  __      _          __  __                                                                    |
[2021-12-08 18:43:57,950] [plex_meta_manager.py:125]  [INFO]     |                                |  _ \| | _____  __ |  \/  | ___| |_ __ _  |  \/  | __ _ _ __   __ _  __ _  ___ _ __                                  |
[2021-12-08 18:43:57,951] [plex_meta_manager.py:126]  [INFO]     |                                | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|                                 |
[2021-12-08 18:43:57,951] [plex_meta_manager.py:127]  [INFO]     |                                |  __/| |  __/>  <  | |  | |  __/ || (_| | | |  | | (_| | | | | (_| | (_| |  __/ |                                    |
[2021-12-08 18:43:57,951] [plex_meta_manager.py:128]  [INFO]     |                                |_|   |_|\___/_/\_\ |_|  |_|\___|\__\__,_| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|                                    |
[2021-12-08 18:43:57,952] [plex_meta_manager.py:129]  [INFO]     |                                                                                                     |___/                                            |
[2021-12-08 18:43:57,952] [plex_meta_manager.py:130]  [INFO]     |     Version: 1.13.2                                                                                                                                  |
[2021-12-08 18:43:57,953] [util.py:197]               [DEBUG]    |======================================================================================================================================================|
[2021-12-08 18:43:57,953] [plex_meta_manager.py:141]  [DEBUG]    | --config (PMM_CONFIG): None                                                                                                                          |
[2021-12-08 18:43:57,954] [plex_meta_manager.py:142]  [DEBUG]    | --time (PMM_TIME): 6:00                                                                                                                              |
[2021-12-08 18:43:57,954] [plex_meta_manager.py:143]  [DEBUG]    | --run (PMM_RUN): True                                                                                                                                |
[2021-12-08 18:43:57,954] [plex_meta_manager.py:144]  [DEBUG]    | --run-tests (PMM_TEST): False                                                                                                                        |
[2021-12-08 18:43:57,955] [plex_meta_manager.py:145]  [DEBUG]    | --collections-only (PMM_COLLECTIONS_ONLY): False                                                                                                     |
[2021-12-08 18:43:57,955] [plex_meta_manager.py:146]  [DEBUG]    | --libraries-only (PMM_LIBRARIES_ONLY): False                                                                                                         |
[2021-12-08 18:43:57,955] [plex_meta_manager.py:147]  [DEBUG]    | --run-collections (PMM_COLLECTIONS): None                                                                                                            |
[2021-12-08 18:43:57,956] [plex_meta_manager.py:148]  [DEBUG]    | --run-libraries (PMM_LIBRARIES): None                                                                                                                |
[2021-12-08 18:43:57,956] [plex_meta_manager.py:149]  [DEBUG]    | --resume (PMM_RESUME): None                                                                                                                          |
[2021-12-08 18:43:57,956] [plex_meta_manager.py:150]  [DEBUG]    | --no-countdown (PMM_NO_COUNTDOWN): False                                                                                                             |
[2021-12-08 18:43:57,957] [plex_meta_manager.py:151]  [DEBUG]    | --no-missing (PMM_NO_MISSING): False                                                                                                                 |
[2021-12-08 18:43:57,957] [plex_meta_manager.py:152]  [DEBUG]    | --divider (PMM_DIVIDER): =                                                                                                                           |
[2021-12-08 18:43:57,957] [plex_meta_manager.py:153]  [DEBUG]    | --width (PMM_WIDTH): 150                                                                                                                             |
[2021-12-08 18:43:57,958] [plex_meta_manager.py:154]  [DEBUG]    | --debug (PMM_DEBUG): True                                                                                                                            |
[2021-12-08 18:43:57,958] [plex_meta_manager.py:155]  [DEBUG]    | --trace (PMM_TRACE): True                                                                                                                            |
[2021-12-08 18:43:57,959] [plex_meta_manager.py:156]  [DEBUG]    |                                                                                                                                                      |
[2021-12-08 18:43:57,959] [util.py:199]               [INFO]     |======================================================================================================================================================|
[2021-12-08 18:43:57,959] [util.py:206]               [INFO]     |                                                                     Starting Run                                                                     |
[2021-12-08 18:43:57,960] [util.py:210]               [INFO]     |======================================================================================================================================================|
[2021-12-08 18:43:57,960] [config.py:36]              [INFO]     | Locating config...                                                                                                                                   |
[2021-12-08 18:43:57,960] [config.py:42]              [INFO]     | Using //config/config.yml as config                                                                                                                  |
[2021-12-08 18:43:57,998] [util.py:152]               [DEBUG]    | Traceback (most recent call last):                                                                                                                   |
                                                                 |   File "/modules/config.py", line 104, in __init__
                                                                 |     hooks("collection_creation")
                                                                 |   File "/modules/config.py", line 103, in hooks
                                                                 |     changes.extend([w for w in util.get_list(temp.pop(attr), split=False) if w not in changes])
                                                                 | TypeError: 'NoneType' object is not iterable
                                                                 | 
[2021-12-08 18:43:58,000] [util.py:152]               [DEBUG]    | Traceback (most recent call last):
                                                                 |   File "/modules/config.py", line 104, in __init__
                                                                 |     hooks("collection_creation")
                                                                 |   File "/modules/config.py", line 103, in hooks
                                                                 |     changes.extend([w for w in util.get_list(temp.pop(attr), split=False) if w not in changes])
                                                                 | TypeError: 'NoneType' object is not iterable
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "//plex_meta_manager.py", line 162, in start
                                                                 |     config = Config(default_dir, attrs)
                                                                 |   File "/modules/config.py", line 125, in __init__
                                                                 |     raise Failed(f"YAML Error: {e}")
                                                                 | modules.util.Failed: YAML Error: 'NoneType' object is not iterable
                                                                 | 
[2021-12-08 18:43:58,006] [util.py:148]               [CRITICAL] | YAML Error: 'NoneType' object is not iterable
[2021-12-08 18:43:58,006] [plex_meta_manager.py:173]  [INFO]     | 
[2021-12-08 18:43:58,007] [util.py:199]               [INFO]     |======================================================================================================================================================|
[2021-12-08 18:43:58,007] [util.py:206]               [INFO]     |                                                                     Finished Run                                                                     |
[2021-12-08 18:43:58,007] [util.py:206]               [INFO]     |                                                                  Run Time: 0:00:00                                                                   |
[2021-12-08 18:43:58,008] [util.py:210]               [INFO]     |======================================================================================================================================================|
```

**Comment by andrewlef** [comment]
Even though I don't use webhooks, I was able to fix this error by removing the following lines from config.yml:

```
  collection_creation:
  collection_addition:
  collection_removal:
```

I replaced these lines with:

```
  collection_changes:
```

Since certain config file attributes are being deprecated, it would be good if there was some kind of config file error checking that would tell the user to remove certain incompatible attributes from the file.

**Comment by meisnate12** [comment]
so the error was in the automatic change of the three attributes to one attribute so that why i didn't include a change log of attributes because all old attributes still work even if undocumented now develop will have the auto change fixed
