### ISSUE TITLE
Script no longer runs after latest update: KeyError: 'tautulli'

### ISSUE THREAD

**Issue by doctarrwho** [Kometa-Team/Kometa#51]
```
[2021-02-21 20:31:43,720] [config.py:24]              [INFO]     | Locating config...                                                                                 |
[2021-02-21 20:31:43,721] [config.py:29]              [INFO]     | Using /mnt/c/repos/unraid/Plex-Meta-Manager/config/config.yml as config                            |
[2021-02-21 20:31:43,746] [util.py:594]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "plex_meta_manager.py", line 76, in start
                                                                 |     config = Config(default_dir, config_path)
                                                                 |   File "/mnt/c/repos/unraid/Plex-Meta-Manager/modules/config.py", line 69, in __init__
                                                                 |     new_config["tautulli"] = new_config.pop("tautulli")
                                                                 | KeyError: 'tautulli'
                                                                 | 
[2021-02-21 20:31:43,747] [plex_meta_manager.py:80]   [CRITICAL] | 'tautulli'
```
Using `master` branch. I dont have tautulli defined in the config file.

**Comment by meisnate12** [comment]
fix should be in
