### ISSUE TITLE
Bug: Collection Error: No Builders were found

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#523]
**Describe the Bug**
I thought this had something to do with me trying to add `collection_mode: hide` to a bunch of my collections, but I get this error now even with that line commented out. I noticed recently that a lot of my previously working collections are now giving this error, and I have no clue why. But I'm assuming it's the reason my collections aren't updating as expected.

**Relevant Collection Config**
```
  "Action":
    sort_title: +Action
    collection_mode: hide
    smart_filter:
      sort_by: title.desc
      all:
        genre: Action
        collection.not:
          - .Animation
          - .YouTube
        label.not: Anime
```
**Plex Meta Manager Info**
Version: 1.13.3-develop1217

**Link to logs (required)**
```
[2021-12-19 06:34:56,738] [util.py:200]               [INFO]     |====================================================================================================|
[2021-12-19 06:34:56,738] [util.py:207]               [INFO]     |                                         Action Collection                                          |
[2021-12-19 06:34:56,739] [util.py:211]               [INFO]     |====================================================================================================|
[2021-12-19 06:34:56,739] [plex_meta_manager.py:958]  [INFO]     |                                                                                                    |
[2021-12-19 06:34:56,739] [util.py:207]               [INFO]     |=================================== Validating Action Attributes ===================================|
[2021-12-19 06:34:56,739] [builder.py:1412]           [INFO]     |                                                                                                    |
[2021-12-19 06:34:56,739] [builder.py:1413]           [INFO]     | Validating Method: smart_filter                                                                    |
[2021-12-19 06:34:56,740] [builder.py:1419]           [DEBUG]    | Value: ordereddict([('sort_by', 'title.desc'), ('all', ordereddict([('genre', 'Action'), ('collection.not', ['.Animation', '.YouTube']), ('label.not', 'Anime')]))]) |
[2021-12-19 06:34:57,032] [builder.py:547]            [DEBUG]    |                                                                                                    |
[2021-12-19 06:34:57,032] [builder.py:548]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2021-12-19 06:34:57,032] [builder.py:549]            [DEBUG]    | Value: +Action                                                                                     |
[2021-12-19 06:34:57,032] [builder.py:547]            [DEBUG]    |                                                                                                    |
[2021-12-19 06:34:57,033] [builder.py:548]            [DEBUG]    | Validating Method: collection_mode                                                                 |
[2021-12-19 06:34:57,033] [builder.py:549]            [DEBUG]    | Value: hide                                                                                        |
[2021-12-19 06:34:57,033] [util.py:153]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 965, in run_collection
                                                                 |     builder = CollectionBuilder(config, library, metadata, mapping_name, no_missing, collection_attrs)
                                                                 |   File "/modules/builder.py", line 600, in __init__
                                                                 |     raise Failed(f"{self.Type} Error: No builders were found")
                                                                 | modules.util.Failed: Collection Error: No builders were found
                                                                 | 
[2021-12-19 06:34:57,034] [util.py:150]               [ERROR]    | Collection Error: No builders were found
[2021-12-19 06:34:57,038] [plex_meta_manager.py:1073] [INFO]     | 
[2021-12-19 06:34:57,039] [util.py:200]               [INFO]     |====================================================================================================|
[2021-12-19 06:34:57,040] [util.py:207]               [INFO]     |                                     Finished Action Collection                                     |
[2021-12-19 06:34:57,040] [util.py:207]               [INFO]     |                                    Collection Run Time: 0:00:00                                    |
[2021-12-19 06:34:57,040] [util.py:211]               [INFO]     |====================================================================================================|

**Comment by meisnate12** [comment]
should be fixed in develop
