### ISSUE TITLE
With 1.2.2, a missing yml file results in the entire process not running

### ISSUE THREAD

**Issue by Tharic99** [Kometa-Team/Kometa#55]
After the upgrade to 1.2.2 and the automatic changes to my `config.yml` file, I noticed that PMM wasn't running. 

It turns out it was missing a `TV Shows.yml` file and that was causing it to not run. Here's the log info.

```
|====================================================================================================|
[2021-02-22 11:48:39,863] [util.py:637]               [INFO]     |====================================================================================================|
[2021-02-22 11:48:39,864] [plex_meta_manager.py:55]   [INFO]     |                                                                                                    |
[2021-02-22 11:48:39,864] [plex_meta_manager.py:56]   [INFO]     |        ____  _             __  __      _          __  __                                           |
[2021-02-22 11:48:39,865] [plex_meta_manager.py:57]   [INFO]     |       |  _ \| | _____  __ |  \/  | ___| |_ __ _  |  \/  | __ _ _ __   __ _  __ _  ___ _ __         |
[2021-02-22 11:48:39,865] [plex_meta_manager.py:58]   [INFO]     |       | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|        |
[2021-02-22 11:48:39,865] [plex_meta_manager.py:59]   [INFO]     |       |  __/| |  __/>  <  | |  | |  __/ || (_| | | |  | | (_| | | | | (_| | (_| |  __/ |           |
[2021-02-22 11:48:39,866] [plex_meta_manager.py:60]   [INFO]     |       |_|   |_|\___/_/\_\ |_|  |_|\___|\__\__,_| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|           |
[2021-02-22 11:48:39,866] [plex_meta_manager.py:61]   [INFO]     |                                                                            |___/                   |
[2021-02-22 11:48:39,866] [plex_meta_manager.py:62]   [INFO]     |           Version: 1.2.2                                                                           |
[2021-02-22 11:48:39,866] [util.py:637]               [INFO]     |====================================================================================================|
[2021-02-22 11:48:39,867] [util.py:637]               [INFO]     |====================================================================================================|
[2021-02-22 11:48:39,867] [util.py:639]               [INFO]     |                                            Starting Run                                            |
[2021-02-22 11:48:39,867] [util.py:640]               [INFO]     |====================================================================================================|
[2021-02-22 11:48:39,867] [config.py:24]              [INFO]     | Locating config...                                                                                 |
[2021-02-22 11:48:39,868] [config.py:29]              [INFO]     | Using //config/config.yml as config                                                                |
[2021-02-22 11:48:39,916] [util.py:637]               [INFO]     |====================================================================================================|
[2021-02-22 11:48:39,920] [cache.py:37]               [INFO]     | Using cache database at //config/config.cache                                                      |
[2021-02-22 11:48:39,922] [util.py:594]               [DEBUG]    | Config Warning: No Paths exist using ['//config/assets'] as default                                |
[2021-02-22 11:48:39,922] [util.py:637]               [INFO]     |====================================================================================================|
[2021-02-22 11:48:39,922] [config.py:159]             [INFO]     | Connecting to TMDb...                                                                              |
[2021-02-22 11:48:40,025] [config.py:165]             [INFO]     | TMDb Connection Successful                                                                         |
[2021-02-22 11:48:40,026] [util.py:637]               [INFO]     |====================================================================================================|
[2021-02-22 11:48:40,026] [config.py:173]             [INFO]     | Connecting to Trakt...                                                                             |
[2021-02-22 11:48:40,215] [config.py:183]             [INFO]     | Trakt Connection Successful                                                                        |
[2021-02-22 11:48:40,215] [util.py:637]               [INFO]     |====================================================================================================|
[2021-02-22 11:48:40,475] [config.py:192]             [INFO]     | Connecting to My Anime List...                                                                     |
[2021-02-22 11:48:40,475] [config.py:201]             [ERROR]    | Config Error: mal sub-attribute client_id is blank                                                 |
[2021-02-22 11:48:40,476] [config.py:202]             [INFO]     | My Anime List Connection Failed                                                                    |
[2021-02-22 11:48:40,944] [util.py:637]               [INFO]     |====================================================================================================|
[2021-02-22 11:48:40,947] [config.py:212]             [INFO]     | Connecting to Plex Libraries...                                                                    |
[2021-02-22 11:48:40,950] [util.py:637]               [INFO]     |====================================================================================================|
[2021-02-22 11:48:40,951] [config.py:254]             [INFO]     | Connecting to Movies Library...                                                                    |
[2021-02-22 11:48:42,393] [plex.py:46]                [INFO]     | Using Asset Directory: //config/assets                                                             |
[2021-02-22 11:48:42,394] [config.py:275]             [INFO]     | Movies Library Connection Successful                                                               |
[2021-02-22 11:48:42,394] [config.py:282]             [INFO]     | Connecting to Movies library's Radarr...                                                           |
[2021-02-22 11:48:42,415] [config.py:296]             [INFO]     | Movies library's Radarr Connection Successful                                                      |
[2021-02-22 11:48:42,415] [config.py:299]             [INFO]     | Connecting to Movies library's Sonarr...                                                           |
[2021-02-22 11:48:42,509] [config.py:313]             [INFO]     | Movies library's Sonarr Connection Successful                                                      |
[2021-02-22 11:48:42,509] [config.py:316]             [INFO]     | Connecting to Movies library's Tautulli...                                                         |
[2021-02-22 11:48:42,550] [config.py:324]             [INFO]     | Movies library's Tautulli Connection Successful                                                    |
[2021-02-22 11:48:42,551] [util.py:637]               [INFO]     |====================================================================================================|
[2021-02-22 11:48:42,551] [config.py:254]             [INFO]     | Connecting to TV Shows Library...                                                                  |
[2021-02-22 11:48:42,553] [util.py:594]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 76, in start
                                                                 |     config = Config(default_dir, config_path)
                                                                 |   File "/modules/config.py", line 268, in __init__
                                                                 |     params["metadata_path"] = check_for_attribute(libs[lib], "metadata_path", var_type="path", default=os.path.join(default_dir, "{}.yml".format(lib)), throw=True)
                                                                 |   File "/modules/config.py", line 124, in check_for_attribute
                                                                 |     message = "neither {} or the default path {} could be found".format(data[attribute], default)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/comments.py", line 753, in __getitem__
                                                                 |     return ordereddict.__getitem__(self, key)
                                                                 | KeyError: 'metadata_path'
                                                                 | 
[2021-02-22 11:48:42,556] [plex_meta_manager.py:80]   [CRITICAL] | 'metadata_path'
[2021-02-22 11:48:42,601] [plex_meta_manager.py:81]   [INFO]     | 
[2021-02-22 11:48:42,603] [util.py:637]               [INFO]     |====================================================================================================|
[2021-02-22 11:48:42,604] [util.py:639]               [INFO]     |                                            Finished Run                                            |
[2021-02-22 11:48:42,605] [util.py:640]               [INFO]     |====================================================================================================|
```

Previously, without a `TV Shows.yml` file, it still ran fine. 

Solution - Created a `TV Shows.yml` file and populated it with a blank collection. 

You may want to add an error check in for this though.

**Comment by meisnate12** [comment]
fix is in dev
