### ISSUE TITLE
Feature Request - Filter by duration

### ISSUE THREAD

**Issue by meisnate12** [Kometa-Team/Kometa#66]
add a filter for duration 

[original request from PAC](https://github.com/mza921/Plex-Auto-Collections/issues/207)

**Comment by miguelamaral** [comment]
Maybe I'm missing something obvious, but I can't get this to work. Any idea why I'm getting `Unknown Error: 'duration'` using version 1.4.0 and PMS 1.21.4.4079?

```
60–90 Minutes:
    plex_all: true
    filters:
        duration.gte: 60
        duration.lte: 89

---

Traceback (most recent call last):
  File "[xxx]/.apps/plex-meta-manager/modules/config.py", line 461, in update_libraries
    builder.run_methods(collection_obj, collection_name, rating_key_map, movie_map, show_map)
  File "[xxx]/.apps/plex-meta-manager/modules/builder.py", line 726, in run_methods
    if len(items) > 0:                                  rating_key_map = self.library.add_to_collection(collection_obj if collection_obj else collection_name, items, self.filters, self.details["show_filtered"], rating_key_map, movie_map, show_map)
  File "[xxx]/.apps/plex-meta-manager/modules/plex.py", line 133, in add_to_collection
    method = util.filter_alias[filter_method[:-4]] if modifier in [".not", ".lte", ".gte"] else util.filter_alias[filter_method]
KeyError: 'duration'

Unknown Error: 'duration'
```

I've also downgraded from the stable version of PMS (1.22.0.4163) as it seems to have broken Plex Search (as seen in https://github.com/meisnate12/Plex-Meta-Manager/issues/78). However I don't think that's related to this? Thanks.

**Comment by meisnate12** [comment]
yea the PMS version isn't the problem I got the fix in develop now tho if you wanna try it out

**Comment by miguelamaral** [comment]
Mmm, I'm still getting the same error.

```
Traceback (most recent call last):
  File "[xxx]/.apps/plex-meta-manager/modules/config.py", line 463, in update_libraries
    builder.run_methods(collection_obj, collection_name, rating_key_map, movie_map, show_map)
  File "[xxx]/.apps/plex-meta-manager/modules/builder.py", line 749, in run_methods
    if len(items) > 0:                                  rating_key_map = self.library.add_to_collection(collection_obj if collection_obj else collection_name, items, self.filters, self.details["show_filtered"], rating_key_map, movie_map, show_map)
  File "[xxx]/.apps/plex-meta-manager/modules/plex.py", line 139, in add_to_collection
    method_name = util.filter_alias[filter_method[:-4]] if modifier in [".not", ".lte", ".gte"] else util.filter_alias[filter_method]
KeyError: 'duration'

Unknown Error: 'duration'
```

**Comment by meisnate12** [comment]
your image wasn't updated properly because this line was taken out of the code completely. Try redownloading from develop 
```python
 method_name = util.filter_alias[filter_method[:-4]] if modifier in [".not", ".lte", ".gte"] else util.filter_alias[filter_method]
```

**Comment by miguelamaral** [comment]
It's actually still there, see https://github.com/meisnate12/Plex-Meta-Manager/blob/develop/modules/plex.py#L139.

Commented it out, it works!

**Comment by meisnate12** [comment]
lmao i rewrote the operation around it and forgot to take out the original line my bad haha just pushed the update to develop

**Comment by miguelamaral** [comment]
Hahah, been there. Thanks again for the quick fix!
