### ISSUE TITLE
Bug:  If 1 series fail to be added every single one in bulk add also fails.

### ISSUE THREAD

**Issue by Drapersniper** [Kometa-Team/Kometa#693]
**Describe the Bug**
```[2022-02-04 17:02:27,056] [sonarr.py:69]              [DEBUG]    | Sonarr Adds: [312559, 307061, 316814, 315164, 315103, 300835, 289884, 316332, 314286, 272129, 313867, 289882, 316815, 317802, 311149, 318271, 315094, 315093, 309202, 308030, 314287, 316837, 310436, 315098, 81115, 317454, 317682, 278975, 314267, 317206, 314482, 316998, 321496, 316844, 250070, 309203, 317830, 316334, 312665, 291726, 306267, 304106, 314284, 315100, 339076, 321234, 316331, 316049, 315092, 315091, 282059, 317391, 309143, 289796, 314480, 300110, 79237, 262856, 317566, 315099, 304110, 304476, 257755, 245821, 315095, 308036, 293647, 309201, 317829, 317820, 167131, 283930, 277063, 309151, 167921, 299536, 311832, 317865, 316838, 261667, 309148, 309152] |
[2022-02-04 17:03:03,589] [util.py:158]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 733, in run_collection
                                                                 |     radarr_add, sonarr_add = builder.run_missing()
                                                                 |   File "/modules/builder.py", line 1826, in run_missing
                                                                 |     added_to_sonarr += self.library.Sonarr.add_tvdb(missing_tvdb_ids, **self.sonarr_details)
                                                                 |   File "/modules/sonarr.py", line 130, in add_tvdb
                                                                 |     _a, _e, _i = self.api.add_multiple_series(shows, folder, quality_profile, language_profile, monitor,
                                                                 |   File "/usr/local/lib/python3.9/site-packages/arrapi/apis/sonarr.py", line 328, in add_multiple_series
                                                                 |     series.extend([Series(self, data=s) for s in self._raw.post_series_import(json[i:i+per_request])])
                                                                 |   File "/usr/local/lib/python3.9/site-packages/arrapi/raws/sonarr.py", line 26, in post_series_import
                                                                 |     return self._post("series/import", json=json)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/arrapi/raws/base.py", line 40, in _post
                                                                 |     return self._request("post", path, json=json, **kwargs)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/arrapi/raws/base.py", line 83, in _request
                                                                 |     raise ArrException(f"({response.status_code} [{response.reason}]) {response_json[0]['errorMessage']}")
                                                                 | arrapi.exceptions.ArrException: (400 [Bad Request]) Title slug 'duel-masters' is in use by series 'Duel Masters'
                                                                 | 
[2022-02-04 17:03:03,591] [plex_meta_manager.py:789]  [ERROR]    | Unknown Error: (400 [Bad Request]) Title slug 'duel-masters' is in use by series 'Duel Masters'
```

**Relevant Collection Config**
- Add missing to Arr (Sonarr)
Other settings aren't relevant for this specific crash.

**Plex Meta Manager Info**
-   Version: 1.14.1 

**Link to logs (required)**
- If having an error with a specific collection include the collection.log otherwise please include the full meta.log file on [Gist](http://gist.github.com). _Do not upload attachments_.

In the ideal scenario, the script would catch this error then attempt to iterate through the list instead of bulk so that only the single series fails, I haven't tried it with Radarr to see if it's reproducible but I assume it would be the same issue (the difference with Radarr and sonarr is that sonarr used a title slug based on a series name which is prone to conflict while Radarr uses TMDB ids which will be almost never conflict (only scenario I can think of is if a movie is deleted and the ID is reused)

Just to clarify when this error happens the script carries onto the next collection which means that the collection where this happened fails to be added to Arr/Plex

**Comment by meisnate12** [comment]
Update to the newest version and this shouldn't be an issue

**Comment by Drapersniper** [comment]
> Update to the newest version and this shouldn't be an issue

Ah awesome thanks I had the docker imagine pinned for some reason and didn't realise and thought I was on latest.

thanks for the quick reply!
