### ISSUE TITLE
"Schedule" tag does not appear to function

### ISSUE THREAD

**Issue by jfeeser** [Kometa-Team/Kometa#71]
Hi there,

I've got an issue with the scheduling functionality in PMM.  I have an entry for a movie collection on tmdb:

```
   Berserk Golden Age Arc Collection:
     tmdb_collection: 118415
     sort_title: 00 - 10 - Collections - Berserk
     sync_mode: sync
     schedule: monthly(1)
     summary: Berserk Golden Age Arc is a series of films covering the backstory of the manga Berserk.
     collection_order: release
```

The collection creates properly if i comment out the "schedule" tag, but if it's uncommented i get this in the log:

```
[2021-02-25 17:21:33,225] [util.py:637]               [INFO]     |====================================================================================================|
[2021-02-25 17:21:33,226] [util.py:639]               [INFO]     |                            Berserk Golden Age Arc Collection Collection                            |
[2021-02-25 17:21:33,226] [util.py:640]               [INFO]     |====================================================================================================|
[2021-02-25 17:21:33,226] [config.py:370]             [INFO]     |                                                                                                    |
[2021-02-25 17:21:33,226] [util.py:594]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/config.py", line 374, in update_libraries
                                                                 |     builder = CollectionBuilder(self, library, c, collections[c])
                                                                 |   File "/modules/builder.py", line 141, in __init__
                                                                 |     self.schedule += "\nScheduled monthly on the {}".format(util.make_ordinal(param))
                                                                 | TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
                                                                 |
[2021-02-25 17:21:33,227] [config.py:377]             [ERROR]    | unsupported operand type(s) for +=: 'NoneType' and 'str'
[2021-02-25 17:21:33,227] [config.py:368]             [INFO]     |

```
Is this a bug or am i doing something wrong?

**Comment by meisnate12** [comment]
the fix should be in the develop branch can you test?

**Comment by jfeeser** [comment]
Dumb question of the day - i'm running PMM in docker, how do i swap it to the develop branch?

**Comment by meisnate12** [comment]
No dumb questions!

if you're using a docker command like the one below
`docker run -it -v "X:\Media\Plex Meta Manager\config:/config:rw" meisnate12/plex-meta-manager`
then all you need to do is add `:<TAG_NAME>` at the end like this
`docker run -it -v "X:\Media\Plex Meta Manager\config:/config:rw" meisnate12/plex-meta-manager:develop`

if you're installing your image a different way like through a GUI it usually asks you which version when your adding it and it just defaults to latest unless you change it. 

If you're still having trouble let me know what system docker is running on so i can see if i can figure out how to help you

**Comment by doctarrwho** [comment]
If you're using unraid, you can specify the branch in the UI like this:

![image](https://user-images.githubusercontent.com/70813119/109345176-bf22d000-783d-11eb-848b-b92ccfd71b58.png)

When no branch is specified (it would show `meisnate12/plex-meta-manager`), which means it defaults to `latest`

**Comment by jfeeser** [comment]
Thanks!  Unraid all the way.  After upgrading it and not changing anything else other than adding :develop i now get this:

```
[2021-02-26 14:37:05,270] [util.py:660]               [INFO]     |====================================================================================================|
[2021-02-26 14:37:05,270] [util.py:662]               [INFO]     |                            Berserk Golden Age Arc Collection Collection                            |
[2021-02-26 14:37:05,270] [util.py:663]               [INFO]     |====================================================================================================|
[2021-02-26 14:37:05,270] [config.py:370]             [INFO]     |                                                                                                    |
[2021-02-26 14:37:05,271] [util.py:617]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/config.py", line 374, in update_libraries
                                                                 |     builder = CollectionBuilder(self, library, c, collections[c])
                                                                 |   File "/modules/builder.py", line 163, in __init__
                                                                 |     raise Failed(f"Skipping Collection {self.name}")
                                                                 | modules.util.Failed: Skipping Collection Berserk Golden Age Arc Collection
                                                                 |
[2021-02-26 14:37:05,272] [config.py:377]             [ERROR]    | Skipping Collection Berserk Golden Age Arc Collection

```

**Comment by meisnate12** [comment]
thats the correct output the collection is set to run on the 1st of the month so it should run tomorrow otherwise it'll be skipped. The stack trace shouldn't have printed in the debug so I'm gonna fix that and add a display saying when its going to run.

**Comment by jfeeser** [comment]
Awesome.  Thanks for the quick turnaround!

**Comment by meisnate12** [comment]
ok the output should be more informative now
