### ISSUE TITLE
Plex_search unknown filter

### ISSUE THREAD

**Issue by bobokun** [Kometa-Team/Kometa#78]
I am seeing a lot of errors in the log where plex_search isn't working anymore. This worked in a previous version but I can't seem to figure out if it's a bug or something wrong with my config.

### Studio
```
[2021-03-03 16:49:47,487] [util.py:703]               [INFO]     |====================================================================================================|
[2021-03-03 16:49:47,487] [util.py:707]               [INFO]     |                               Illumination Entertainment Collection                                |
[2021-03-03 16:49:47,487] [util.py:708]               [INFO]     |====================================================================================================|
[2021-03-03 16:49:47,487] [config.py:373]             [INFO]     |                                                                                                    |
[2021-03-03 16:49:47,488] [builder.py:192]            [INFO]     | Scanning Illumination Entertainment Collection                                                     |
[2021-03-03 16:49:47,488] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:49:47,488] [builder.py:220]            [DEBUG]    | Method: template                                                                                   |
[2021-03-03 16:49:47,488] [builder.py:221]            [DEBUG]    | Value: ordereddict([('name', 'Studio'), ('studio', 'Illumination Entertainment')])                 |
[2021-03-03 16:49:47,488] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:49:47,488] [builder.py:220]            [DEBUG]    | Method: summary                                                                                    |
[2021-03-03 16:49:47,488] [builder.py:221]            [DEBUG]    | Value: Illumination is an American film and animation studio founded by Chris Meledandri in 2007 and owned by Universal Pictures, a division of NBCUniversal, which is itself a division of Comcast. Meledandri produces the films, while Universal finances and distributes all the films. The studio is responsible for the Despicable Me and The Secret Life of Pets franchises and the film adaptations of Dr. Seuss’ books The Lorax and How the Grinch Stole Christmas. The Minions, characters from the Despicable Me series, are the studio's mascots. |
[2021-03-03 16:49:47,489] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:49:47,489] [builder.py:220]            [DEBUG]    | Method: plex_search                                                                                |
[2021-03-03 16:49:47,489] [builder.py:221]            [DEBUG]    | Value: {'studio': 'Illumination Entertainment'}                                                    |
[2021-03-03 16:49:47,489] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:49:47,489] [builder.py:220]            [DEBUG]    | Method: sort_title                                                                                 |
[2021-03-03 16:49:47,489] [builder.py:221]            [DEBUG]    | Value: +++_Illumination Entertainment                                                              |
[2021-03-03 16:49:47,489] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:49:47,489] [builder.py:220]            [DEBUG]    | Method: collection_order                                                                           |
[2021-03-03 16:49:47,489] [builder.py:221]            [DEBUG]    | Value: release                                                                                     |
[2021-03-03 16:49:47,495] [config.py:396]             [INFO]     |                                                                                                    |
[2021-03-03 16:49:47,496] [config.py:398]             [INFO]     | Sync Mode: sync                                                                                    |
[2021-03-03 16:49:47,628] [builder.py:570]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:49:47,628] [builder.py:571]            [DEBUG]    | Method: plex_search                                                                                |
[2021-03-03 16:49:47,628] [builder.py:572]            [DEBUG]    | Values: [[('studio', ['Illumination Entertainment'])]]                                             |
[2021-03-03 16:49:47,628] [builder.py:592]            [INFO]     |                                                                                                    |
[2021-03-03 16:49:47,629] [builder.py:593]            [DEBUG]    | Value: [('studio', ['Illumination Entertainment'])]                                                |
[2021-03-03 16:49:47,629] [builder.py:613]            [INFO]     | Processing Plex Search: studio(Illumination Entertainment)                                         |
[2021-03-03 16:49:47,636] [util.py:660]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/config.py", line 410, in update_libraries
                                                                 |     builder.run_methods(collection_obj, collection_name, rating_key_map, movie_map, show_map)
                                                                 |   File "/modules/builder.py", line 614, in run_methods
                                                                 |     items = self.library.Plex.search(**search_terms)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/library.py", line 668, in search
                                                                 |     args[category] = self._cleanSearchFilter(category, value, libtype)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/library.py", line 717, in _cleanSearchFilter
                                                                 |     raise BadRequest('Unknown filter category: %s' % category)
                                                                 | plexapi.exceptions.BadRequest: Unknown filter category: studio
                                                                 | 
[2021-03-03 16:49:47,637] [config.py:425]             [ERROR]    | Unknown Error: Unknown filter category: studio
```
### Actor
```
[2021-03-03 16:54:55,494] [util.py:703]               [INFO]     |====================================================================================================|
[2021-03-03 16:54:55,494] [util.py:707]               [INFO]     |                                      Adam Sandler Collection                                       |
[2021-03-03 16:54:55,494] [util.py:708]               [INFO]     |====================================================================================================|
[2021-03-03 16:54:55,494] [config.py:373]             [INFO]     |                                                                                                    |
[2021-03-03 16:54:55,495] [builder.py:192]            [INFO]     | Scanning Adam Sandler Collection                                                                   |
[2021-03-03 16:54:55,571] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:54:55,571] [builder.py:220]            [DEBUG]    | Method: template                                                                                   |
[2021-03-03 16:54:55,572] [builder.py:221]            [DEBUG]    | Value: ordereddict([('name', 'Actor Writer'), ('person', 19292)])                                  |
[2021-03-03 16:54:55,572] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:54:55,572] [builder.py:220]            [DEBUG]    | Method: actor                                                                                      |
[2021-03-03 16:54:55,572] [builder.py:221]            [DEBUG]    | Value: tmdb                                                                                        |
[2021-03-03 16:54:55,572] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:54:55,572] [builder.py:220]            [DEBUG]    | Method: writer                                                                                     |
[2021-03-03 16:54:55,572] [builder.py:221]            [DEBUG]    | Value: tmdb                                                                                        |
[2021-03-03 16:54:55,573] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:54:55,573] [builder.py:220]            [DEBUG]    | Method: tmdb_person                                                                                |
[2021-03-03 16:54:55,573] [builder.py:221]            [DEBUG]    | Value: 19292                                                                                       |
[2021-03-03 16:54:55,573] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:54:55,573] [builder.py:220]            [DEBUG]    | Method: sort_title                                                                                 |
[2021-03-03 16:54:55,573] [builder.py:221]            [DEBUG]    | Value: +_Adam Sandler                                                                              |
[2021-03-03 16:54:55,573] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:54:55,573] [builder.py:220]            [DEBUG]    | Method: sync_mode                                                                                  |
[2021-03-03 16:54:55,573] [builder.py:221]            [DEBUG]    | Value: sync                                                                                        |
[2021-03-03 16:54:55,573] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:54:55,574] [builder.py:220]            [DEBUG]    | Method: collection_order                                                                           |
[2021-03-03 16:54:55,574] [builder.py:221]            [DEBUG]    | Value: release                                                                                     |
[2021-03-03 16:54:55,579] [config.py:396]             [INFO]     |                                                                                                    |
[2021-03-03 16:54:55,579] [config.py:398]             [INFO]     | Sync Mode: sync                                                                                    |
[2021-03-03 16:54:55,662] [builder.py:570]            [DEBUG]    |                                                                                                    |
[2021-03-03 16:54:55,662] [builder.py:571]            [DEBUG]    | Method: plex_search                                                                                |
[2021-03-03 16:54:55,662] [builder.py:572]            [DEBUG]    | Values: [[('actor', ['Adam Sandler'])]]                                                            |
[2021-03-03 16:54:55,662] [builder.py:592]            [INFO]     |                                                                                                    |
[2021-03-03 16:54:55,662] [builder.py:593]            [DEBUG]    | Value: [('actor', ['Adam Sandler'])]                                                               |
[2021-03-03 16:54:55,662] [builder.py:613]            [INFO]     | Processing Plex Search: actor(Adam Sandler)                                                        |
[2021-03-03 16:54:55,669] [util.py:660]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/config.py", line 410, in update_libraries
                                                                 |     builder.run_methods(collection_obj, collection_name, rating_key_map, movie_map, show_map)
                                                                 |   File "/modules/builder.py", line 614, in run_methods
                                                                 |     items = self.library.Plex.search(**search_terms)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/library.py", line 668, in search
                                                                 |     args[category] = self._cleanSearchFilter(category, value, libtype)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/library.py", line 717, in _cleanSearchFilter
                                                                 |     raise BadRequest('Unknown filter category: %s' % category)
                                                                 | plexapi.exceptions.BadRequest: Unknown filter category: actor
                                                                 | 
[2021-03-03 16:54:55,670] [config.py:425]             [ERROR]    | Unknown Error: Unknown filter category: actor
```

**Comment by meisnate12** [comment]
I noticed this earlier as well its because the plex API endpoint is different on the beta branch so the plex API dependency now has an error. I've actually already raised the issue [here](https://github.com/pkkid/python-plexapi/issues/595#issuecomment-790049460)

at this moment `plex_search` does not work on the beta branch of PMS

**Comment by bobokun** [comment]
Thanks for clarifying. I downgraded my plex server in the mean time

**Comment by meisnate12** [comment]
follow this PR for updates https://github.com/pkkid/python-plexapi/pull/693

**Comment by meisnate12** [comment]
Plex Search among some other features will not work with Plex Media Server version 1.22 and greater until the above pull request is completed in the meantime you'll have to either downgrade your server version or just wait

**Comment by bobokun** [comment]
I feel bad for all the new issues that are being raised because of this...maybe if there was a way to pin this issue people would see it. Hopefully the pull request will complete soon

**Comment by vitadome** [comment]
I'm partly to blame for the duplicate question.  I should have searched for the issue first but didn't think to until after I posted.

**Comment by meisnate12** [comment]
i can actually pin this issue lol

**Comment by cpt-kuesel** [comment]
is this also the reason why plex_collectionless ignores my filtered collections and just adds every movie to collectionless?

**Comment by meisnate12** [comment]
no this would not cause that. There's a bug with collectionless that i haven't been able to figure out yet

**Comment by cpt-kuesel** [comment]
ah okay, good that you are aware of it then.
#47 is the issue to follow?

**Comment by meisnate12** [comment]
I don't know if it's necessarily the exact same issue do you mind posting your meta.log and metadata file in the other thread so i can see if it helps any

**Comment by jwmoss** [comment]
Looks like [#693](https://github.com/pkkid/python-plexapi/pull/693) was merged. @meisnate12 have you had a chance to validate that it fixes this issue?

**Comment by meisnate12** [comment]
it does and ive been working on the fix update but I don't plan on releasing it until they up the version on plexAPI which should happen shortly
