### ISSUE TITLE
Unknown error: 'tmdb_movie'

### ISSUE THREAD

**Issue by calboi91** [Kometa-Team/Kometa#89]
I get the following error when using `tmdb_movie_details`:

```
[2021-03-06 11:15:13,502] [builder.py:192]            [INFO]     | Scanning STEINS;GATE Collection                                                                    |
[2021-03-06 11:15:13,502] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-06 11:15:13,503] [builder.py:220]            [DEBUG]    | Method: template                                                                                   |
[2021-03-06 11:15:13,503] [builder.py:221]            [DEBUG]    | Value: ordereddict([('name', 'Movie'), ('movie', 225745)])                                         |
[2021-03-06 11:15:13,503] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-06 11:15:13,503] [builder.py:220]            [DEBUG]    | Method: tmdb_movie_details                                                                         |
[2021-03-06 11:15:13,503] [builder.py:221]            [DEBUG]    | Value: 225745                                                                                      |
[2021-03-06 11:15:14,199] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-06 11:15:14,199] [builder.py:220]            [DEBUG]    | Method: sync_mode                                                                                  |
[2021-03-06 11:15:14,199] [builder.py:221]            [DEBUG]    | Value: sync                                                                                        |
[2021-03-06 11:15:14,199] [builder.py:219]            [DEBUG]    |                                                                                                    |
[2021-03-06 11:15:14,199] [builder.py:220]            [DEBUG]    | Method: collection_order                                                                           |
[2021-03-06 11:15:14,199] [builder.py:221]            [DEBUG]    | Value: release                                                                                     |
[2021-03-06 11:15:14,209] [config.py:396]             [INFO]     |                                                                                                    |
[2021-03-06 11:15:14,210] [config.py:398]             [INFO]     | Sync Mode: sync                                                                                    |
[2021-03-06 11:15:14,335] [builder.py:570]            [DEBUG]    |                                                                                                    |
[2021-03-06 11:15:14,335] [builder.py:571]            [DEBUG]    | Method: tmdb_movie                                                                                 |
[2021-03-06 11:15:14,336] [builder.py:572]            [DEBUG]    | Values: [225745]                                                                                   |
[2021-03-06 11:15:14,336] [builder.py:592]            [INFO]     |                                                                                                    |
[2021-03-06 11:15:14,336] [builder.py:593]            [DEBUG]    | Value: 225745                                                                                      |
[2021-03-06 11:15:14,336] [tmdb.py:171]               [DEBUG]    | Data: 225745                                                                                       |
[2021-03-06 11:15:14,337] [tmdb.py:240]               [INFO]     | Processing TMDb Movie: (225745) Steins;Gate: The Movie − Load Region of Déjà Vu (1 Movie)          |
[2021-03-06 11:15:14,337] [tmdb.py:244]               [DEBUG]    | TMDb IDs Found: [225745]                                                                           |
[2021-03-06 11:15:14,337] [tmdb.py:245]               [DEBUG]    | TVDb IDs Found: []                                                                                 |
[2021-03-06 11:15:14,419] [util.py:717]               [INFO]     | STEINS;GATE Collection | = | Steins;Gate: The Movie − Load Region of Déjà Vu                       |
[2021-03-06 11:15:14,420] [util.py:717]               [INFO]     | 1 Movie Processed                                                                                  |
[2021-03-06 11:15:14,420] [builder.py:724]            [INFO]     |                                                                                                    |
[2021-03-06 11:15:14,420] [builder.py:731]            [INFO]     | 0 Movie Removed                                                                                    |
[2021-03-06 11:15:14,420] [builder.py:732]            [INFO]     |                                                                                                    |
[2021-03-06 11:15:14,427] [builder.py:737]            [INFO]     | Detail: tmdb_movie_details updated Collection Summary                                              |
[2021-03-06 11:15:14,474] [builder.py:774]            [INFO]     | Detail: collection_order updated Collection Order to release                                       |
[2021-03-06 11:15:14,474] [builder.py:788]            [DEBUG]    | {'summary.value': 'One year after the events of the anime, Rintarou begins to feel the repercussions of extensive time travel, and eventually completely fades from reality. Kurisu, being the only companion to remember him, now must find a way to bring him back.', 'summary.locked': 1} |
[2021-03-06 11:15:14,639] [builder.py:791]            [INFO]     | Details: have been updated                                                                         |
[2021-03-06 11:15:14,640] [util.py:660]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/home9/calboi/Plex-Meta-Manager/modules/config.py", line 418, in update_libraries
                                                                 |     builder.update_details(plex_collection)
                                                                 |   File "/home9/calboi/Plex-Meta-Manager/modules/builder.py", line 858, in update_details
                                                                 |     elif "tmdb_movie_details" in self.posters:          set_image("tmdb_movie", self.posters)
                                                                 |   File "/home9/calboi/Plex-Meta-Manager/modules/builder.py", line 837, in set_image
                                                                 |     else:                                               collection.uploadPoster(url=images[image_method])
                                                                 | KeyError: 'tmdb_movie'
                                                                 | 
[2021-03-06 11:15:14,640] [config.py:425]             [ERROR]    | Unknown Error: 'tmdb_movie'
```

Similar errors occur when using `tmdb_show_details` or `tmdb_collection_details`. But it seems the collections are updated properly.

**Comment by meisnate12** [comment]
should be fixed in the develop branch
