### ISSUE TITLE
[Bug]: Overlay Error: cannot identify image file 'x/x/x.jpg'

### ISSUE THREAD

**Issue by SaintNick1214** [Kometa-Team/Kometa#930]
### Version Number

1.17.0

### What branch are you on?

master

### Describe the Bug

When running overlay tasks, around 5% of movies throw this error:

`| Traceback (most recent call last):                                                                 |
|   File "/opt/Plex-Meta-Manager/modules/overlays.py", line 170, in run_overlays                     |
|     new_poster = Image.open(poster.location if poster else has_original) \                         |
|   File "/opt/Plex-Meta-Manager/pmm-venv/lib/python3.8/site-packages/PIL/Image.py", line 3123, in open |
|     raise UnidentifiedImageError(                                                                  |
| PIL.UnidentifiedImageError: cannot identify image file '/opt/Plex-Meta-Manager/config/overlays/Movies Original Posters/13420.jpg' |
|                                                                                                    |
| Mystery Date                                                 | Overlay Error: cannot identify image file '/opt/Plex-Meta-Manager/config/overlays/Movies Original Posters/13420.jpg`

I'm not sure when/where these files are added, but it would be good if it could attempt to repair the empty jpg file when it detects this error.

### Logs

https://gist.github.com/SaintNick1214/4b400c95e3857e7af3b84f561d2de2e0

**Comment by SaintNick1214** [comment]
OK I figured it out and it's on plex's side.  If a movie does not have a poster in plex (or if the poster is damaged in plex) then of course PMM will throw an error when attempting to overlay it.
