### ISSUE TITLE
Right out of the gate, no plex connection?

### ISSUE THREAD

**Issue by bigdork** [Kometa-Team/Kometa#99]
Just trying to get all the initial configs done, but no plex libraries? 
Must be something silly, what am I doing wrong that I can't even get Plex talking?

Config:
```
libraries:
  Movies:
    library_type: movie
  TV Shows:
    library_type: show
plex:                                           # Can be individually specified per library as well
  url: https://externalurl
  token: xxxxredactedxxxx
  timeout: 60
```

Output:
```
|           Version: 1.4.0                                                                           |
|====================================================================================================|
|====================================================================================================|
|                                            Starting Run                                            |
|====================================================================================================|
 Locating config...                                                                                 |
| Using /opt/scripts/Plex-Meta-Manager/config/config.yml as config                                   |
|====================================================================================================|
| Using cache database at /opt/scripts/Plex-Meta-Manager/config/config.cache                         |
|====================================================================================================|
| Connecting to TMDb...                                                                              |
| TMDb Connection Successful                                                                         |
|====================================================================================================|
| omdb attribute not found                                                                           |
|====================================================================================================|
| Connecting to Trakt...                                                                             |
| Trakt Connection Successful                                                                        |
|====================================================================================================|
| mal attribute not found                                                                            |
|====================================================================================================|
| Connecting to Plex Libraries...                                                                    |
|====================================================================================================|
| Connecting to Movies Library...                                                                    |
| Movies Library Connection Failed                                                                   |
|====================================================================================================|
| Connecting to TV Shows Library...                                                                  |
| TV Shows Library Connection Failed                                                                 |
|====================================================================================================|
| Plex Error: No Plex libraries were found                                                           |
|                                                                                                    |
|====================================================================================================|
|                                            Finished Run                                            |
|                                         Run Time: 0:00:00
```

**Comment by meisnate12** [comment]
can you post your meta.log file that was generated

**Comment by bigdork** [comment]
```
[2021-03-10 17:17:05,687] [util.py:720]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:05,688] [plex_meta_manager.py:61]   [INFO]     |                                                                                                    |
[2021-03-10 17:17:05,688] [plex_meta_manager.py:62]   [INFO]     |        ____  _             __  __      _          __  __                                           |
[2021-03-10 17:17:05,688] [plex_meta_manager.py:63]   [INFO]     |       |  _ \| | _____  __ |  \/  | ___| |_ __ _  |  \/  | __ _ _ __   __ _  __ _  ___ _ __         |
[2021-03-10 17:17:05,688] [plex_meta_manager.py:64]   [INFO]     |       | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|        |
[2021-03-10 17:17:05,688] [plex_meta_manager.py:65]   [INFO]     |       |  __/| |  __/>  <  | |  | |  __/ || (_| | | |  | | (_| | | | | (_| | (_| |  __/ |           |
[2021-03-10 17:17:05,688] [plex_meta_manager.py:66]   [INFO]     |       |_|   |_|\___/_/\_\ |_|  |_|\___|\__\__,_| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|           |
[2021-03-10 17:17:05,688] [plex_meta_manager.py:67]   [INFO]     |                                                                            |___/                   |
[2021-03-10 17:17:05,688] [plex_meta_manager.py:68]   [INFO]     |           Version: 1.4.0                                                                           |
[2021-03-10 17:17:05,688] [util.py:720]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:05,688] [util.py:720]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:05,688] [util.py:724]               [INFO]     |                                            Starting Run                                            |
[2021-03-10 17:17:05,688] [util.py:725]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:05,688] [config.py:27]              [INFO]     | Locating config...                                                                                 |
[2021-03-10 17:17:05,688] [config.py:32]              [INFO]     | Using /opt/scripts/Plex-Meta-Manager/config/config.yml as config                                   |
[2021-03-10 17:17:05,707] [util.py:720]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:05,708] [cache.py:18]               [INFO]     | Using cache database at /opt/scripts/Plex-Meta-Manager/config/config.cache                         |
[2021-03-10 17:17:05,708] [util.py:677]               [DEBUG]    | Config Warning: No Paths exist using ['/opt/scripts/Plex-Meta-Manager/config/assets'] as default   |
[2021-03-10 17:17:05,708] [util.py:720]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:05,708] [config.py:165]             [INFO]     | Connecting to TMDb...                                                                              |
[2021-03-10 17:17:05,750] [config.py:171]             [INFO]     | TMDb Connection Successful                                                                         |
[2021-03-10 17:17:05,750] [util.py:720]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:05,750] [config.py:188]             [WARNING]  | omdb attribute not found                                                                           |
[2021-03-10 17:17:05,750] [util.py:720]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:05,751] [config.py:194]             [INFO]     | Connecting to Trakt...                                                                             |
[2021-03-10 17:17:05,888] [config.py:204]             [INFO]     | Trakt Connection Successful                                                                        |
[2021-03-10 17:17:05,888] [util.py:720]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:06,113] [config.py:225]             [WARNING]  | mal attribute not found                                                                            |
[2021-03-10 17:17:06,376] [util.py:720]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:06,377] [config.py:234]             [INFO]     | Connecting to Plex Libraries...                                                                    |
[2021-03-10 17:17:06,377] [util.py:720]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:06,378] [config.py:277]             [INFO]     | Connecting to Movies Library...                                                                    |
[2021-03-10 17:17:06,379] [util.py:677]               [DEBUG]    | Config Error: no metadata_path attribute found and the default path None could be found            |
[2021-03-10 17:17:06,380] [config.py:328]             [INFO]     | Movies Library Connection Failed
[2021-03-10 17:17:06,380] [util.py:720]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:06,381] [config.py:277]             [INFO]     | Connecting to TV Shows Library...                                                                  |
[2021-03-10 17:17:06,382] [util.py:677]               [DEBUG]    | Config Error: no metadata_path attribute found and the default path None could be found            |
[2021-03-10 17:17:06,382] [config.py:328]             [INFO]     | TV Shows Library Connection Failed
[2021-03-10 17:17:06,382] [util.py:720]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:06,382] [util.py:677]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "plex_meta_manager.py", line 83, in start
                                                                 |     config = Config(default_dir, config_path)
                                                                 |   File "/opt/scripts/Plex-Meta-Manager/modules/config.py", line 384, in __init__
                                                                 |     raise Failed("Plex Error: No Plex libraries were found")
                                                                 | modules.util.Failed: Plex Error: No Plex libraries were found
                                                                 |
[2021-03-10 17:17:06,382] [plex_meta_manager.py:87]   [CRITICAL] | Plex Error: No Plex libraries were found
[2021-03-10 17:17:06,382] [plex_meta_manager.py:88]   [INFO]     |
[2021-03-10 17:17:06,382] [util.py:720]               [INFO]     |====================================================================================================|
[2021-03-10 17:17:06,382] [util.py:724]               [INFO]     |                                            Finished Run                                            |
[2021-03-10 17:17:06,382] [util.py:724]               [INFO]     |                                         Run Time: 0:00:00                                          |
[2021-03-10 17:17:06,382] [util.py:725]               [INFO]     |====================================================================================================|
```

**Comment by meisnate12** [comment]
so this is your problem:

`Config Error: no metadata_path attribute found and the default path None could be found`

Basically, the program can't find your metadata file for the library.

Do you have a Movies.yml in the same directory as your config.yml?

**Comment by bigdork** [comment]
I just wanted to confirm my Plex/Radarr/etc connections before I dug in, guess I jumped the gun. I'll build out some more and try again.
